namespace :integration do
  namespace :servers do
    namespace :proceed_types do
      task create_or_update: :environment do

        default_proceed_types = [
          ["00807", "UNANIME DESCONTO POR DECISAO JUDICIAL","D"],
          ["02569", "COMPENSACAO POR METAS P/ RED DA CRIMINALIDADE","V"],
          ["02578", "GRAT DE INCENTIVO TECNICO E ADMINISTRATIVO","V"],
          ["02580", "DIFERENCA DE GRAT INCENTIVO TECNICO E ADMINISTRATIVO","V"],
          ["02581", "VALOR DE PARCELA NOMINALMENTE IDENTIFICAVEL","V"],
          ["02586", "GRAT DE FISCAL DE OBRAS DE INFRAEST  DE EDIFICAÇOES","V"],
          ["02589", "GRAT POR TRAB DE CAMPO  DE INFRAEST RODOVIARIA","V"],
          ["02590", "GRAT DE ESTIMULO A REPRESENTACAO JUDICIAL","V"],
          ["02599", "DIF COMPENSACAO POR METAS P/ RED DA CRIMINALIDADE","V"],
          ["02628", "DEV DE DESCONTO DE AUX ALIMENTACAO","V"],
          ["02630", "GRAT POR ENC EM NUCLEO DE ORGAO DE EXEC PROGRAMATICA","V"],
          ["02634", "DEV ADIANT 13 PENSAO ALIMENTO","V"],
          ["02636", "ADPEC e UNIMED","D"],
          ["02637", "DIF FUNPECE FERIAS","V"],
          ["02638", "DEV ADIANT 13 REMUNERACAO MAXIMA","V"],
          ["02639", "RESSARCIMENTO DECIMO TERCEIRO","D"],
          ["02640", "VANT PESSOAL NOMINALMENTE INDENT e FUNTELC","V"],
          ["02645", "RESSARCIMENTO DA REMUNER. MAXIM 13","D"],
          ["02646", "DIFERENCA PENSAO MILITAR SEM INCIDENCIA SUPSEC","V"],
          ["02647", "GRAT DE ATIVID JURIDICA PELA DEFESA DO DESENV SUSTENTAVEL","V"],
          ["02648", "APEOC e ETHERNUS","D"],
          ["02649", "APEOC e ALVORADA","D"],
          ["02650", "DIF FERIAS REVISAO GERAL","V"],
          ["02651", "DIF AUX ALIMENTACAO REVISAO GERAL","V"],
          ["02660", "VPNI DA LEI 15.567/2014","V"],
          ["02661", "DEVOLUCAO DE PENSAO ALIMENTO","V"],
          ["02662", "RRA  DIF EXERCICIO ANTERIOR","V"],
          ["02663", "DEV DA PREVIDENCIA PARLAMENTAR","V"],
          ["02664", "DEPOSITO JUDICIAL3","D"],
          ["02667", "IMPOSTO DE RENDA RRA","D"],
          ["02669", "GITQ e INCENTIVO AO CARGO COMISSIONADO","V"],
          ["02670", "GITQ e PRODUTIVIDADE","V"],
          ["50211", "APEOC e ETHERNUS","D"],
          ["50221", "APEOC e ALVORADA","D"],
          ["50251", "AET e Odonto System","D"],
          ["61091", "ASSTDS e UNIMED","D"],
          ["64511", "CAFAZ e SAUDE","D"],
          ["64521", "CAFAZ e DEPENDENTE","D"],
          ["91091", "ADPEC e UNIMED","D"],
          ["00101", "VENCIMENTO/SALARIO/PROVENTO","V"],
          ["00102", "SUBSIDIOS","V"],
          ["00103", "GRATIFICACAO DE EXERCICIO","V"],
          ["00104", "GRATIFICACAO ESPECIAL","V"],
          ["00105", "REPRESENTACAO DA LEI N. 11.535/89","V"],
          ["00106", "GRAT P/EXERC FUNC EM DETET LOCAIS","V"],
          ["00107", "GRAT PART EM ORGAO DE DELIBERACAO COLETIVA","V"],
          ["00108", "GRATIFICACAO POR TEMPO DE SERVICO","V"],
          ["00109", "GRATIFICACAO DE REPRESENTACAO","V"],
          ["00110", "GRATIFICACAO ABONO POLICIAL CIVIL","V"],
          ["00111", "GRAT DE RISCO DE VIDA OU SAUDE","V"],
          ["00112", "GRAT PELO REGIME DE TEMPO INTEGRAL","V"],
          ["00113", "ADITAMENTO DE JORNADA DE TRABALHO","V"],
          ["00114", "DIFERENCA DE VENCIM/SALARIO/SUBSID","V"],
          ["00115", "GRATIFICACAO DE ENSINO","V"],
          ["00116", "GRAT REP JUDICIAL CONSULT JURIDICA","V"],
          ["00117", "RESPONDENDO POR CARGO EM COMISSAO","V"],
          ["00118", "GRAT ESPEC LOCALIZACAO CARCERARIA","V"],
          ["00119", "FUNCAO COMISSIONADA","V"],
          ["00120", "GRATIFICACAO DEDICACAO EXCLUSIVA","V"],
          ["00121", "AJUDA DE CUSTO","V"],
          ["00122", "DIARIAS","V"],
          ["00123", "SUBSTITUICAO DE CARGO COMISSIONADO","V"],
          ["00124", "DIARIA DE CAMPO","V"],
          ["00125", "GRAT P/ REPRESENTACAO DE GABINETE","V"],
          ["00126", "GRATIFICACAO DE CAMPO","V"],
          ["00127", "GRAT POR SERVICO OU ESTUDO FORA","V"],
          ["00128", "AVISO PREVIO","V"],
          ["00129", "PRESTACAO DE SERVICOS","V"],
          ["00130", "GRAT EXECUCAO TRAB RELEV TEC CIENT","V"],
          ["00131", "GRAT INSTRUT CURSO POLICIAL CIVIL","V"],
          ["00132", "VANTAGEM PESSOAL","V"],
          ["00133", "GRAT DE FUNCAO POLICIAL CIVIL","V"],
          ["00134", "GRAT DE NIVEL UNIVERSITARIO","V"],
          ["00135", "GRAT EM CONDICOES ESPECIAIS","V"],
          ["00136", "FERIAS VENCIDAS","V"],
          ["00137", "FERIAS PROPORCIONAIS","V"],
          ["00138", "FGTS ART 22","V"],
          ["00139", "PRODUTIVIDADE","V"],
          ["00140", "INDENIZACAO DE HORA EXTRA","V"],
          ["00141", "FGTS MES ATUAL","V"],
          ["00142", "GRATIFICACAO DE ESTIPENDIO","V"],
          ["00143", "FGTS MES ANTERIOR","V"],
          ["00144", "DIFERENCA DE GRATIFICACAO","V"],
          ["00145", "GRATIFICACAO DA LEI N. 2.394/54","V"],
          ["00146", "GRAT DA LEI N. 7.066/63  COTAS","V"],
          ["00147", "ADICIONAL DE FERIAS","V"],
          ["00148", "PREeJULGADO","V"],
          ["00149", "ABONO CARCERARIO","V"],
          ["00150", "HORA EXTRA e 50 POR CENTO e","V"],
          ["00151", "HORA EXTRA e 100 POR CENTO e","V"],
          ["00152", "DIF SERV EXTRAORDINARIO/HORA EXTRA","V"],
          ["00153", "VANTAGEM INCORPORADA","V"],
          ["00154", "ADICIONAL DE INSALUBRIDADE","V"],
          ["00155", "SERVICO EXTRAORDINARIO","V"],
          ["00156", "ADICIONAL NOTURNO","V"],
          ["00157", "ADIANTAMENTO DE FERIAS","V"],
          ["00158", "ADICIONAL NOTURNO INCORPORADO","V"],
          ["00159", "GRATIFICACAO DA LEI N. 7.486/64","V"],
          ["00160", "DIARIAS MAIOR QUE 50 POR CENTO","V"],
          ["00161", "VANTAGEM PESSOAL HORA EXTRA INCORPORADA","V"],
          ["00162", "MEDIA FERIAS","V"],
          ["00163", "ADIANTAMENTO DO 13 SALARIO","V"],
          ["00164", "COMPLEMENTACAO DE PROVENTOS","V"],
          ["00165", "SALARIO MATERNIDADE","V"],
          ["00166", "GRATIFICACAO DA LEI N. 4.196/58","V"],
          ["00167", "GRATIFICACAO DA LEI N. 7.999/65","V"],
          ["00168", "ADICIONAL DE FUNCAO","V"],
          ["00169", "GRATIFICACAO DA LEI N. 8.384/66","V"],
          ["00170", "TRANFERENCIA DE EMPREGADO","V"],
          ["00171", "GRAT DE REPRESENTACAO INCORPORADA","V"],
          ["00172", "DIFERENCA DE FERIAS","V"],
          ["00173", "INDENIZACAO DE LICENCA PREMIO","V"],
          ["00174", "PAGAMENTO AULAS","V"],
          ["00175", "GRATIFICACAO DE PLANTAO NOTURNO","V"],
          ["00176", "GRATIFICACAO POR EVENTOS","V"],
          ["00177", "ABONO DE FERIAS","V"],
          ["00178", "GRAT T RECURSAL","V"],
          ["00179", "DIFERENCA DE ASCENSAO","V"],
          ["00180", "GRATIFICACAO COMISSAO DE LICITACAO","V"],
          ["00181", "COMPLEMENTO SALARIAL","V"],
          ["00182", "COMPLEMENTO SALARIAL e INSS","V"],
          ["00183", "GRAT DE EFETIVA REGENCIA DE CLASSE","V"],
          ["00184", "DIFERENCA DE PROGRESSAO HORIZONTAL","V"],
          ["00185", "GRAT EFETIVO EXERC ESPECIALIDADE","V"],
          ["00186", "GRAT A PROFESSORES DE EXCEPCIONAIS","V"],
          ["00187", "DEVOLUCAO DE REMUNERACAO MAXIMA","V"],
          ["00188", "INDENIZACAO OU AUXILIO A MORADIA","V"],
          ["00189", "PRODUTIVIDADE POR DECISAO JUDICIAL","V"],
          ["00190", "DEVOLUCAO DE IMPOSTO DE RENDA","V"],
          ["00191", "GRATIFICACAO DO ARTIGO 155","V"],
          ["00192", "GRAT DE PERICIA MEDICA E TECNICA","V"],
          ["00193", "DIFERENCA DE PENSAO ALIMENTICIA","V"],
          ["00194", "DIFERENCA DECIMO TERCEIRO SALARIO","V"],
          ["00195", "DECIMO TERCEIRO SALARIO","V"],
          ["00196", "OPERACAO RADAR","V"],
          ["00197", "BOLSA DE ESTUDO","V"],
          ["00198", "GRAT DE DIRECAO E LEGISLACAO","V"],
          ["00199", "PENSAO ALIMENTICIA","V"],
          ["00200", "SALARIO EDUCACAO","V"],
          ["00201", "INDENIZACAO DE REPRESENTACAO","V"],
          ["00202", "SOLDO / VENCIMENTO","V"],
          ["00203", "GRATIFICACAO POR TEMPO DE SERVICO","V"],
          ["00204", "INDENIZACAO FUNCAO POL MILITAR","V"],
          ["00205", "GRAT DE REPRESENTACAO DE GABINETE","V"],
          ["00206", "GRAT EXERCICIO NO INTERIOR ESTADO","V"],
          ["00207", "GRATIFICACAO REPRESENTACAOeMILITAR","V"],
          ["00208", "GRATIFICACAO DE 1/3 SOBRE O SOLDO","V"],
          ["00209", "DIFERENCA DE SOLDO OU VENCIMENTO","V"],
          ["00210", "INDENIZACAO DA HABILITACAO MILITAR","V"],
          ["00211", "GRATIFICACAO DE ENSINO e MILITAR","V"],
          ["00212", "GRATIFICACAO DE MAGISTERIO","V"],
          ["00213", "DIFERENCA DE GRATIFICACAO","V"],
          ["00214", "INDENIZACAO DE MORADIA e MILITAR","V"],
          ["00215", "GRAT RISCO DE VIDA/SAUDE MILITAR","V"],
          ["00216", "INCENT AO DESENVOLV PROFISSIONAL","V"],
          ["00217", "GRATIFICACAO ATIVIDADE FUNCIONAL","V"],
          ["00218", "GRATIFICACAO DA LEI N. 10.206/78","V"],
          ["00219", "DEVOLUCAO DE FA","V"],
          ["00220", "DIFERENCA DE SALARIO EDUCACAO","V"],
          ["00221", "AJUDA DE CUSTO e MILITAR","V"],
          ["00222", "DIARIAS e MILITAR","V"],
          ["00223", "ETAPAS PARA ALIMENTACAO","V"],
          ["00224", "AJUDA PARA FARDAMENTO","V"],
          ["00225", "GRAT DE DESEMPENHO FAZENDARIO","V"],
          ["00226", "GRATIFICACAO INCENTIVO MOTORISTA","V"],
          ["00227", "GRAT DE DELEGADO OU SUBDELEGADO","V"],
          ["00228", "INDENIZACAO ADICIONAL INATIVIDADE","V"],
          ["00229", "DIARIAS OPERACIONAIS","V"],
          ["00230", "GRAT DE LICENCA EXTRAORDINARIA","V"],
          ["00231", "GRATIFICACAO INCORPORADA","V"],
          ["00232", "DIFERENCA INCORPORADA","V"],
          ["00233", "DEVOLUCAO DESC INDEV S/INCIDENCIA","V"],
          ["00234", "VANTAGEM INCORPORADA DA SAUDE","V"],
          ["00235", "INDENIZACAO DE FERIAS","V"],
          ["00236", "VANTAGEM PESSOAL DO PCC","V"],
          ["00237", "INCENTIVO APERFEICOAM E QUALIDADE","V"],
          ["00238", "GRAT ESPECIAL DE DESEMPENHO","V"],
          ["00239", "GRAT MONITORAMENTO CLIMATICO","V"],
          ["00240", "VANTAGEM POR DECISAO JUDICIAL","V"],
          ["00241", "GRAT DESEMPENHO ATIVIDADES OBRAS","V"],
          ["00242", "GRATIFICACAO EXTERNA","V"],
          ["00243", "VANTAGEM INCORPORADA DA FEBEMCE","V"],
          ["00244", "VANTAGEM PESSOAL DA LEI 12.287/94","V"],
          ["00245", "VANTAGEM DE EXERCICIO ANTERIOR","V"],
          ["00246", "AJUDA FARDAMENTO COM RESTITUICAO","V"],
          ["00247", "EMPRESTIMO/ADIANTAMENTO DE FERIAS","V"],
          ["00248", "GRATIFICACAO DE AUDITOR","V"],
          ["00249", "GRATIFICACAO JUDICIARIA","V"],
          ["00250", "GRATIFICACAO DE ESPECIALIZACAO","V"],
          ["00251", "GRATIFICACAO DA LEI 12.482/95","V"],
          ["00252", "GRAT MEMBROS CONSELHO MAGISTRADO","V"],
          ["00253", "COMPLEMENTO REMUNERATORIO","V"],
          ["00254", "DIFERENCA COMPLEM REMUNERATORIO","V"],
          ["00255", "GRATIFICACAO DE VOO","V"],
          ["00256", "PARCELA DE DESEMPENHO MINISTERIAL","V"],
          ["00257", "VANTAGEM PESSOAL e QUINTOS","V"],
          ["00258", "ABONO COMPENSATORIO","V"],
          ["00259", "REPOSICAO DE FALTAS","V"],
          ["00260", "DIFERENCA DE DIARIAS","V"],
          ["00261", "DIF GRATIFICACAO DE REPRESENTACAO","V"],
          ["00262", "DIFERENCA BOLSA TRABALHO / ESTAGIO","V"],
          ["00263", "RESIDENCIA MEDICA","V"],
          ["00264", "BOLSA DE TRABALHO / ESTAGIO","V"],
          ["00265", "DIFERENCA URV","V"],
          ["00266", "ADIANTAMENTO DE SALARIO","V"],
          ["00267", "GRAT INCENTIVO CENTRO PROCES DADOS","V"],
          ["00268", "GRATIFICACAO DE FUNCAO","V"],
          ["00269", "ABONO FAZENDARIO","V"],
          ["00270", "PARCELA POR DECISAO JUDICIAL","V"],
          ["00271", "COMPLEMENTO POR DECISAO JUDICIAL","V"],
          ["00272", "DIFERENCA DE AMPLIAC CARGA HORARIA","V"],
          ["00273", "ADICIONAL DE PERICULOSIDADE","V"],
          ["00274", "ADICIONAL DE INSALUBRIDADE","V"],
          ["00275", "GRATIFICACAO DE LOCOMOCAO","V"],
          ["00276", "MEMB JUNTA REC","V"],
          ["00277", "GRATIFICACAO DE PROJETO","V"],
          ["00278", "AUXILIO ALIMENTACAO","V"],
          ["00279", "GRAT DIR TCM","V"],
          ["00280", "REPRESENTACAO TCM","V"],
          ["00281", "GRAT INCENTIVO PROFISSIONAL","V"],
          ["00282", "GRATIFICACAO EXTRA CLASSE","V"],
          ["00283", "GRAT EXECUCAO OBRAS E TRANSPORTES","V"],
          ["00284", "GRAT INCENT PESQ DESENVOLVIMENTO","V"],
          ["00285", "DIFERENCA DE PRESTACAO DE SERVICOS","V"],
          ["00286", "PARC AD DESEMP","V"],
          ["00287", "GRATIFICACAO CONSELHO FISCAL","V"],
          ["00288", "GRATIFICACAO DE INSTRUTOR","V"],
          ["00289", "PROLABORE","V"],
          ["00290", "GRAT DE TRABALHO TECNICOeJURIDICO","V"],
          ["00291", "U R P","V"],
          ["00292", "DIFERENCA ASCENSAO EXERC ANTERIOR","V"],
          ["00293", "DIFERENCA P H EXERCICIO ANTERIOR","V"],
          ["00294", "DEVOLUCAO IPEC","V"],
          ["00295", "DEVOLUCAO PENSAO ALIMEN/REM MAXIMA","V"],
          ["00296", "VANT DA LEI 9.660/72 EX COMBATENTE","V"],
          ["00297", "RESSARCIMENTO DO SUPSEC","V"],
          ["00298", "DIFERENCA DIARIAS OPERACIONAIS","V"],
          ["00299", "EMPRESTIMO SALDO NEGATIVO","V"],
          ["00301", "PROVENTO","V"],
          ["00302", "GRATIFICACAO DE REPRESENTACAO TJ","V"],
          ["00303", "INDENIZACAO DE TRANSPORTE","V"],
          ["00304", "DIF SEM INCIDENCIA DE SUPSEC","V"],
          ["00305", "DIF GRAT TRAB TECNICO RELEVANTE","V"],
          ["00306", "DEVOLUCAO INSS","V"],
          ["00307", "PREMIO POR DESEMPENHO FISCAL","V"],
          ["00308", "DIFERENCA PREMIO DESEMPENHO FISCAL","V"],
          ["00309", "AUXILIO MESTRE DA CULTURA","V"],
          ["00310", "CUSTAS","V"],
          ["00311", "VENC APOSENTADORIA PROPORCIONAL","V"],
          ["00312", "PERCENTUAL DE CUSTAS","V"],
          ["00313", "GRATIFICACAO SOBRE O VENCIMENTO","V"],
          ["00314", "GRAT ESP RADIOPATRULHAMENTO AEREO","V"],
          ["00315", "GRATIFICACAO REMUNERATORIA","V"],
          ["00316", "AMPLIACAO DE CARGA HORARIA","V"],
          ["00317", "EMPRESTIMO LICENCA EXTRAORDINARIA","V"],
          ["00318", "VANTAGEM DA LEI 13.250/2002","V"],
          ["00319", "CARGO DE PROVIMENTO EM COMISSAO","V"],
          ["00320", "REMUNERACAO","V"],
          ["00321", "DIFERENCA DE REMUNERACAO","V"],
          ["00322", "GRATIFICACAO MILITAR","V"],
          ["00323", "GRATIFICACAO QUALIFICACAO POLICIAL","V"],
          ["00324", "GRAT QUALIFICACAO BOMBERISTICA","V"],
          ["00325", "GRAT ATIVIDADE POLICIA JUDICIARIA","V"],
          ["00326", "GRATIFICACAO ATIVIDADE JUDICIARIA","V"],
          ["00327", "GRAT ATVIDADE DEFENSORIA PUBLICA","V"],
          ["00328", "GRAT DESEMP DE ATIVIDADE AUDITORIA","V"],
          ["00329", "DIFERENCA DE GDAA","V"],
          ["00330", "GRAT. ESPECIFICA DE PROCURADOR","V"],
          ["00331", "DIF DE GDAA EXERCICIO ANTERIOR","V"],
          ["00332", "DIFERENCA DE RESIDENCIA MEDICA","V"],
          ["00333", "DEVOLUCAO DESC INDEV C/ INCIDENCIA","V"],
          ["00334", "GRATIFICACAO ESPECIAL DE EXERCICIO","V"],
          ["00335", "DIF. GRAT TRAB MONI CLIM","V"],
          ["00336", "DIFERENCA GRAT ESPECIAL DESEMPENHO","V"],
          ["00337", "GRATIFICACAO REPRESENTACAO FUNCAO","V"],
          ["00338", "AUXILIO RECLUSO","V"],
          ["00339", "DIFERENA DE AUXILIO MORADIA","V"],
          ["00340", "DIFERENCA DE PROVENTO","V"],
          ["00341", "DIF SERVICO EXTRAORDIN RIO","V"],
          ["00342", "DIFERENA ACORDO JUDICIAL DERT","V"],
          ["00343", "ACORDO JUDICIAL DERT","V"],
          ["00344", "AUXILIO MENSAL TEMPORARIO","V"],
          ["00345", "DIF AUXILIO MENSAL TEMPORARIO","V"],
          ["00346", "GRATIFICACAO POR TITULACAO","V"],
          ["00347", "PREMIO POR APREENSAO DE ARMAS","V"],
          ["00348", "GRAT INCENT AO TRABA C/QUALIDADE","V"],
          ["00349", "RESSARCIMENTO DE PROVENTOS","V"],
          ["00350", "GRAT DESEMP DE ANALISE DE GESTAO","V"],
          ["00351", "DIF GRAT DESENP ANALISE DE GESTAO","V"],
          ["00352", "GRAT DESEMP ATIV DA TECNO INFORMA","V"],
          ["00353", "DIF GRAT DESENP ATIV DA TECNO INFO","V"],
          ["00354", "GRAT DESEMP DE ATIV PLANEJ ORCAMEN","V"],
          ["00355", "DIF GRAT DESEMP PLANEJ E ORCAMENTO","V"],
          ["00356", "IND REFORCO SERV MILITAR OPERACION","V"],
          ["00357", "GRAT DE DESEMP DE ATIVID REGULACAO","V"],
          ["00358", "DIF GRAT DE DESEMP DE ATIVID REGUL","V"],
          ["00359", "GRAT DESEMP DE ATIV ANALIS POL PUB","V"],
          ["00360", "GRAT. ATIV DE PLANT FINAL SEMANA","V"],
          ["00361", "DIF GRAT DESEMP ATIV ANAL POL PUBL","V"],
          ["00362", "GRAT REP AGUARDANDO APOSENTADORIA","V"],
          ["00363", "GRAT DIRETOR HOSPITAL/ ESCOLA E SUPERITENDENTE","V"],
          ["00380", "PROGRAMA DEMISSAO VOLUNTARIA COHAB","V"],
          ["00381", "INDENIZACAO","V"],
          ["00382", "PENSAO ALIMENT PROG DEMIS VOLUNT","V"],
          ["00383", "PENSAO ALIMENTICIA e INDENIZACAO","V"],
          ["00401", "PENSAO MILITAR","V"],
          ["00402", "PENSAO CIVIL","V"],
          ["00403", "DIFERENCA PENSAO CIVIL","V"],
          ["00404", "DIFERENCA PENSAO MILITAR","V"],
          ["00405", "DIFERENCA PENSAO EXERC ANTERIOR","V"],
          ["00406", "INDENIZACAO POR ACAO JUDICIAL","V"],
          ["00407", "FUNCAO GRATIFICADA","V"],
          ["00408", "PENSAO ESPECIAL","V"],
          ["00409", "PENSAO INDENIZATORIA","V"],
          ["00410", "PLANTAO ESPECIAL","V"],
          ["00411", "GRATIFICACAO DE SUBSTITUICAO","V"],
          ["00412", "DIFERENCA AUXILIO ALIMENTACAO","V"],
          ["00413", "AUXILIO AO EXCEPCIONAL","V"],
          ["00414", "DIF DE VANTAGEM S INCIDENCIA","V"],
          ["00415", "DEVOLUCAO DE MONTEPIO","V"],
          ["00416", "PENSAO PROVISORIA","V"],
          ["00417", "DIFERENCA DE PENSAO PROVISORIA","V"],
          ["00418", "DIFERENCA PENSAO PROV EXERC ANTER","V"],
          ["00419", "DIFERENCA PENSAO ESPECIAL","V"],
          ["00420", "DIFERENÇA DE ABONO DE PERMANENCIA","V"],
          ["00421", "PENSAO VITALICIA","V"],
          ["00422", "DIFERENCA DE PENSÃO VITALICIA","V"],
          ["00425", "PIS PASEP","V"],
          ["00429", "FUNCAO COM EQUIPAMENTO OU VEICULO","V"],
          ["00430", "ABONO DE PERMANENCIA","V"],
          ["00431", "INDENIZACAO e MORTE","V"],
          ["00432", "PREMIO EDUCACAO","V"],
          ["00433", "ABONO PROVISORIO","V"],
          ["00434", "ADIC INDIVIDUAL","V"],
          ["00435", "DIFERENCA DE ABONO SALARIAL","V"],
          ["00436", "ABONO SALARIAL","V"],
          ["00437", "ABONO POLICIAL MILITAR","V"],
          ["00438", "ABONO DA LEI N. 11.917/1991","V"],
          ["00439", "ABONO LEGISTA","V"],
          ["00440", "ABONO DA LEI N.12.541/1995","V"],
          ["00501", "SALARIO FAMILIA","V"],
          ["00506", "DIFERENCA DE SALARIO FAMILIA","V"],
          ["00551", "AUXILIO DOENCA","V"],
          ["00552", "AUXILIO FUNERAL","V"],
          ["00553", "AUXILIO INVALIDEZ","V"],
          ["00554", "DIF AUX DOENCA","V"],
          ["00556", "AUXILIO NATALIDADE","V"],
          ["00557", "AUXILIO NATALIDADE","V"],
          ["00558", "DIFERENCA OU QUEBRA DE CAIXA","V"],
          ["00559", "AUXILIO CRECHE / ESCOLA","V"],
          ["00599", "VALOR DO FGTS","V"],
          ["00601", "IPEC CONTRIB","D"],
          ["00602", "LIQ. RECISAO","D"],
          ["00603", "*              "],
          ["00604", "IPEC EMP SAUDE","D"],
          ["00605", "IPEC EMP SIMPL","D"],
          ["00606", "IPEC EMP EMERG","D"],
          ["00608", "IPEC PEC ADIC","D"],
          ["00609", "IPEC EMP NUPCIA","D"],
          ["00610", "ASSOC S C BR C","D"],
          ["00612", "IMPOSTO DE REND","D"],
          ["00613", "INDENIZACAO","D"],
          ["00614", "MONTEP MILITAR","D"],
          ["00615", "MONTEP CIVIL","D"],
          ["00616", "ALUGUEL IMOVEL","D"],
          ["00617", "PENSAO ALIMENT","D"],
          ["00618", "ASPEC CONTRIB","D"],
          ["00619", "RESSARCIMENTO AUXILIO ALIMENTACAO","D"],
          ["00620", "ACSPC CONTR","D"],
          ["00621", "ACSPC SERV COLT","D"],
          ["00622", "AMB SEGUROS","D"],
          ["00623", "CAPEMISA CONTRIB","D"],
          ["00624", "MULTA DO TRIB. DE CONTAS DO ESTADO","D"],
          ["00625", "GBOEX CONTRIB","D"],
          ["00626", "FEDERAL SEGUROS","D"],
          ["00627", "ASSOC SERV 1","D"],
          ["00628", "CIA S MINAS BR","D"],
          ["00629", "VALE TRANSPORTE","D"],
          ["00630", "SUL AMER BAND","D"],
          ["00631", "MONGERAL PREVID","D"],
          ["00632", "ODONTO SYSTEM","D"],
          ["00633", "CX BENEFIC PMC","D"],
          ["00634", "CX BENEFIC SEG","D"],
          ["00635", "CX BEN SER PRES","D"],
          ["00636", "SUL AMER S VIDA","D"],
          ["00637", "SINSECE MOVA SE","D"],
          ["00638", "ASES CONTRIB","D"],
          ["00639", "FARDAMENTO","D"],
          ["00640", "UNIDONTO","D"],
          ["00641", "UNIMED","D"],
          ["00642", "CX BEN 25 SET C","D"],
          ["00643", "SAMEG","D"],
          ["00644", "CLUB COL FER 1","D"],
          ["00645", "COIFA CONTRIB","D"],
          ["00646", "GR B O INAT C","D"],
          ["00647", "GR B O INAT E","D"],
          ["00648", "CONASP","D"],
          ["00649", "ASERPUB","D"],
          ["00650", "INSS","D"],
          ["00651", "ASPEC SEG COLET","D"],
          ["00652", "REAL PREV SEG","D"],
          ["00653", "CONT SINDICAL","D"],
          ["00654", "RESTITUICAO","D"],
          ["00655", "UNASP","D"],
          ["00656", "ASS CLASSE I","D"],
          ["00657", "ACMeASSIST.MEDICO HOSPITALAR","D"],
          ["00658", "ATRASO","D"],
          ["00659", "FALTAS","D"],
          ["00660", "DESPESA ANULAR","D"],
          ["00661", "DESPESA ANULAR DO SALARIOeFAMILIA","D"],
          ["00662", "REM MAXIMA","D"],
          ["00663", "ASS CLASSE II","D"],
          ["00664", "ASS CLASSE III","D"],
          ["00665", "DEV IMP RENDA","D"],
          ["00666", "DIF PENSAO ALIM","D"],
          ["00667", "HAP VIDA","D"],
          ["00668", "RESSARCIMENTO","D"],
          ["00669", "PREVDENT","D"],
          ["00670", "CBF A SP CONT","D"],
          ["00671", "BRASILPREV","D"],
          ["00672", "CEF EMPRESTIMO","D"],
          ["00673", "UNIODONTO","D"],
          ["00674", "SASEC CONTRIB","D"],
          ["00675", "ASPB CONTRIB","D"],
          ["00676", "AGUANAMBI SAUDE","D"],
          ["00677", "DESAFIO JOVEM","D"],
          ["00678", "PREVIPLAN CLUB","D"],
          ["00679", "FORTSAUDE","D"],
          ["00680", "ADIANT FERIAS","D"],
          ["00681", "RSPP PREV PRIV","D"],
          ["00682", "EMPREST FERIAS","D"],
          ["00683", "FUND ESP PMC","D"],
          ["00684", "FUNDESP PMC IND","D"],
          ["00685", "ASSOC SER 2","D"],
          ["00686", "UBASP CONTRIB","D"],
          ["00687", "FUNDO CRISTAO","D"],
          ["00688", "AMAL CONTRIBUIC","D"],
          ["00689", "UNIAO BENEFIC DE ASSISTE SERV PUB","D"],
          ["00690", "UISP SEGUROS","D"],
          ["00691", "RESSARC CAPES","D"],
          ["00692", "ASSOC SERV 3","D"],
          ["00693", "COHABeCE","D"],
          ["00694", "SINFITO CE","D"],
          ["00695", "SIND DOS FARMACEUTICO DO CEARA","D"],
          ["00696", "CORRFA CONTRIB","D"],
          ["00697", "BIBLIOTECA TJC","D"],
          ["00698", "ADIANT 13 SAL","D"],
          ["00699", "CONT ANIVERSAR","D"],
          ["00700", "CORSEC SEGUROS","D"],
          ["00701", "CAIXA ECON HABITACAO","D"],
          ["00702", "SINTAF","D"],
          ["00703", "YORKSHIRE","D"],
          ["00704", "GENERALI SEGURO","D"],
          ["00705", "DEVOL SALDO NEG","D"],
          ["00706", "DEVOL PREMIO DESEMPENHO FISCAL","D"],
          ["00707", "CAFAZ CORRETORA","D"],
          ["00708", "CAFAZ INDENIZAC","D"],
          ["00709", "CAFAZ DEPENDENT","D"],
          ["00710", "DIFERENCA IPEC","D"],
          ["00711", "CAFAZ","D"],
          ["00712", "ASS CLASSE IV","D"],
          ["00713", "GEPLAN CONTRIB","D"],
          ["00714", "AUDITECE","D"],
          ["00715", "CASEBRAS","D"],
          ["00716", "ASSOC CE MIN PU","D"],
          ["00717", "SUSPENSAO","D"],
          ["00718", "GREMIO REC OFIC","D"],
          ["00719", "INDEN PREJUIZO","D"],
          ["00720", "CLUB COL FER 2","D"],
          ["00721", "MULTA","D"],
          ["00722", "ACASP CONTRIB","D"],
          ["00723", "SINDICATO 1","D"],
          ["00724", "RESSARC  DETRAN","D"],
          ["00725", "EMPREST COMUM","D"],
          ["00726", "ASS.VIUVAS.PMC","D"],
          ["00727", "INST MAGIST CE","D"],
          ["00728", "INST MAGIST BR","D"],
          ["00729", "APECE","D"],
          ["00730", "DESC ADVOGADO","D"],
          ["00731", "ADIANT SALARIO","D"],
          ["00732", "DESPESA COMPROV","D"],
          ["00733", "MONT SER P BR C","D"],
          ["00734", "ASSOC ENG AGRON","D"],
          ["00735", "SIND ENGE CE","D"],
          ["00736", "SINDICATO 2","D"],
          ["00737", "EMPREST IMOBIL","D"],
          ["00738", "SINDICATO 3","D"],
          ["00739", "SIND JORNALISTA","D"],
          ["00740", "SINDICATO 4","D"],
          ["00741", "SINDICATO 5","D"],
          ["00742", "G B S R","D"],
          ["00743", "RSPP PREV PRIV","D"],
          ["00744", "DENTAL SEGUROS","D"],
          ["00745", "LUMEN  AD VIAM","D"],
          ["00746", "ODONT TIME LIFE","D"],
          ["00747", "SUDAMERIS EMP","D"],
          ["00748", "CLINDONTO","D"],
          ["00749", "BAMERINDUS","D"],
          ["00750", "ASSIST BUC SERV","D"],
          ["00751", "BNB INFORMATICA","D"],
          ["00752", "CONFUNASP CONTR","D"],
          ["00753", "CONFUNASP EMPRE","D"],
          ["00754", "DESC ART 124 VI","D"],
          ["00755", "DESCONTO CRECHE","D"],
          ["00756", "RESTAURANTE FAZ","D"],
          ["00757", "IRTERMED","D"],
          ["00758", "ASSOC CABOS/SOL","D"],
          ["00759", "UNIPSICO","D"],
          ["00760", "CESTA BASICA","D"],
          ["00761", "RESSARCIM H EXT","D"],
          ["00762", "ASSOC DOS SERV PUBLICOS BRASILEIRO","D"],
          ["00763", "MPS SEG GRUPO","D"],
          ["00764", "CAFAZ SAUDE","D"],
          ["00765", "CAFAZ ESTACIONAMENTO","D"],
          ["00766", "CAMED","D"],
          ["00767", "DEVOLUCAO ABONO PERMANENCIA","D"],
          ["00768", "SINDERT ACORDO JUDICIAL","D"],
          ["00769", "UNIPUBLI CONT","D"],
          ["00770", "DESP ANUL S/PRE","D"],
          ["00771", "AUSENCIA","D"],
          ["00772", "RESSARCIMENTO DA REMUNER. MAXIM","D"],
          ["00776", "RESSARCIMENTO PARA O INSS","D"],
          ["00777", "DEV PREVIDENC AMPLIACAO DEFINITIVA","D"],
          ["00779", "ASSOC SERV 4","D"],
          ["00783", "ASS TRES SET C","D"],
          ["00784", "ASS TRES SET E","D"],
          ["00789", "IPREDE","D"],
          ["00790", "ASS CLASSE V","D"],
          ["00791", "ASS CLASSE VI","D"],
          ["00792", "CABEMCE C BASIC","D"],
          ["00793", "CABEMCE FARMAC","D"],
          ["00794", "CABEMCE FARDAM","D"],
          ["00795", "SEG FUNCIONARIO","D"],
          ["00796", "ASSOC SERV 5","D"],
          ["00797", "ATRICON","D"],
          ["00798", "ABRACCON","D"],
          ["00799", "CABEMCE TRANSP","D"],
          ["00800", "CABEMCE P SAUDE","D"],
          ["00801", "CABEMCE P HABIT","D"],
          ["00802", "ASSOC DOS PREVIDENCIARIOS SERV PUB","D"],
          ["00803", "FONOAUDIOLOGA","D"],
          ["00804", "CABEMCE EMPREST","D"],
          ["00805", "DES ANUL FERIAS","D"],
          ["00806", "COHAB","D"],
          ["00809", "CLUB ATL B V SE","D"],
          ["00810", "OBOE FINANCEIRA","D"],
          ["00811", "BANCO SUDAMERIS","D"],
          ["00815", "FUNDO PENITENCI","D"],
          ["00820", "DESCONTO PREVIDENCIA","D"],
          ["00821", "DEVOLUCAO PARA SUPSEC","D"],
          ["00824", "IPEC EMP FUNER","D"],
          ["00831", "ASS NAC MIN PUB","D"],
          ["00834", "AUX ALIMENTACAO","D"],
          ["00835", "DEVOLUCAO DE PROVENTOS","D"],
          ["00838", "INDENIZ PEN ALI","D"],
          ["00839", "PDVI PEN ALIMEN","D"],
          ["00841", "PREVIMIL CONT","D"],
          ["00846", "CAPBOM e CAIXA ASSIST PECULIO BOMB","D"],
          ["00847", "GR S BRANDINHO","D"],
          ["00848", "GR CABO ANSELMO","D"],
          ["00850", "BEC INFORMAT 2","D"],
          ["00851", "CIA U C SEG A P","D"],
          ["00852", "BEC INFORMAT  1","D"],
          ["00853", "BEC SEGURO","D"],
          ["00854", "BRADESCO EMPRESTIMO","D"],
          ["00855", "BEC HABITACAO","D"],
          ["00856", "CLUBE EXECUTIVO","D"],
          ["00857", "BIC EMPRESTIMO","D"],
          ["00858", "BANCO DO BRASIL e EMPRESTIMO","D"],
          ["00860", "IMP S SERV ISS","D"],
          ["00862", "BRASIL CRED","D"],
          ["00865", "DIFERENCA INSS","D"],
          ["00868", "ASSOCIBRAS CONT","D"],
          ["00869", "CASPEB","D"],
          ["00871", "DINAM CLUB SEG","D"],
          ["00873", "UFEC CONTRIB","D"],
          ["00875", "PROQUALITY AACC","D"],
          ["00878", "PROeSOCIAL CONT","D"],
          ["00882", "Generali Seguro","D"],
          ["00895", "PENSAO ANTECIPA","D"],
          ["00896", "DIFERENCA URV","D"],
          ["00899", "EMP SALDO NEGAT","D"],
          ["00900", "CEDAP  PEIXE","D"],
          ["00903", "LIVRARIA","D"],
          ["00905", "GNPP SEG SA CON","D"],
          ["00906", "RSPP PREV PRIV","D"],
          ["00910", "ASSC CONTRIBUICAO","D"],
          ["00911", "FARMACIA","D"],
          ["00914", "CONVENIO SESI","D"],
          ["00927", "UNIAO ASSISTENCIAS DOS SERV BRASIL","D"],
          ["00956", "IND ACAO JUDICI","D"],
          ["00957", "DEPOSITO JUDICIAL","D"],
          ["00959", "GOLDEN CROSS","D"],
          ["00967", "BRADESCOeSEGURO","D"],
          ["00978", "FUNDAC ASSIST 1","D"],
          ["00979", "FUNDAC ASSIST 2","D"],
          ["00986", "CONTA EMPREGADO","D"],
          ["00988", "PROBAL","D"],
          ["00994", "CLUB/COL FER 3","D"],
          ["00995", "CLUB/COL FER 4","D"],
          ["00996", "ASSOC DOS PRACAS DA PM E BM","D"],
          ["00997", "MBM CONTRIB","D"],
          ["00384", "PDF 13 SALARIO","V"],
          ["00998", "VALOR BRUTO","D"],
          ["00365", "DIFERENCA SUBSIDIOS","V"],
          ["00400", "DOACAO","V"],
          ["00999", "VALOR LIQUIDO","D"],
          ["00366", "DIFERENCA DE PENSAO INDENIZATORIA","V"],
          ["00822", "PREVIDENCIA PARLAMENTAR","D"],
          ["00364", "ABONO DO GRUPO MAS","V"],
          ["00611", "DOACAO","D"],
          ["00950", "CONSIGNACOES FACULTATIVAS","D"],
          ["00447", "FINANCIAMENTO CURSOS POS GRADUACAO","V"],
          ["00367", "DIF GRAT DED EXCLUS L 14005/07","V"],
          ["00368", "ADIANTAMENTO DA LEI 14.112 APJS","V"],
          ["00369", "GRAT DE POLICIAMENTO OSTENSIVO","V"],
          ["00370", "DIF DE VANTAGEM DECISAO JUDICIAL","V"],
          ["00371", "GRAT POR ENCARGOS DE LICITACAO","V"],
          ["00372", "COMPLEMENTO SUBSIDIO","V"],
          ["00373", "DIF GRAT POR ENCARGOS DE LICITACAO","V"],
          ["00374", "DIF GRAT POLICIAMENTO OSTENSIVO","V"],
          ["00375", "PARCELA NOMINALMENTE IDENTIFICAVEL","V"],
          ["00376", "GRAT COMISSAO CONCURSO","V"],
          ["00377", "ABONO DE FERIAS SEM INCIDENCIA","V"],
          ["00378", "DIFERENCA DE REAJUSTE","V"],
          ["00379", "DIF MEDIA PDF FERIAS","V"],
          ["00385", "ADIC DE PREMIO POR DESEMP FISCAL","V"],
          ["00386", "DIF ADIC DE PREMIO POR DESEMP FISC","V"],
          ["00387", "GRAT DE ATIVIDADE MEDICO PERICIAL","V"],
          ["00388", "PREMIO DESEMPENHO FUNPECE","V"],
          ["00389", "COMPLEMENTO PISO MAGISTERIO","V"],
          ["00390", "GRAT POR EXERC NA ATIV DE INTELIG","V"],
          ["00391", "COMPLEMENTO DE PRODUTIVIDADE","V"],
          ["00392", "ABONO MAGISTERIO 1 2 GRAUS","V"],
          ["00393", "AUXILIO TRANSPORTE","V"],
          ["00394", "DIF AUXILIO TRANSPORTE","V"],
          ["00395", "GRAT ENSINO DE PRATICAS MEDICAS","V"],
          ["00396", "GRAT DE DESEMPENHO AMBIENTAL","V"],
          ["00397", "COMPL PROVISORIO DA REMUN MINIMA","V"],
          ["00398", "PARCELA DECISAO JUDICIAL/DETRAN","V"],
          ["00399", "ABONO DA LEI 14582","V"],
          ["00441", "GRATIFICACAO DE DESEMPENHO MILITAR","V"],
          ["00442", "PREMIO APRENDER PRA VALER","V"],
          ["00443", "FUNPECE FERIAS","V"],
          ["00444", "DEVOLUCAO DE REMUN MAXIMA FUNPECE","V"],
          ["00445", "DIF DE ASCENSAO ANTERIOR A 2008","V"],
          ["00446", "PREMIO FUNPECE 13 SALARIO","V"],
          ["00448", "DIFERENCA PISO MAGISTERIO","V"],
          ["00449", "GRAT ENCARGO DE ANALISE CALC JUDIC","V"],
          ["00450", "GRAT DESEMP ATIV GERENC PROJETOS","V"],
          ["00451", "COMPL DO LIMITE MINIMO PDF","V"],
          ["00452", "DIF COMPL MINIMO PDF","V"],
          ["00453", "ADICIONAL COMPL MINIMO PDF FERIAS","V"],
          ["00454", "DIF ADIC COMPL MINIMO PDF FERIAS","V"],
          ["00455", "ADICIONAL PDF FERIAS","V"],
          ["00456", "DIF ADICIONAL PDF  FERIAS","V"],
          ["00457", "GRAT DA LEI 14.969/2011","V"],
          ["00458", "COMPLEMENTO DA LEI 14.969/2011","V"],
          ["00459", "DIF DE PENSAO SEFAZ","V"],
          ["00460", "GRAT DESEMP ATIV DEFESA AGROPECUAR","V"],
          ["00461", "PARC NOMIN IDENTIF LEI 15.009/2011","V"],
          ["00462", "GRAT ATIV DISCIPLINAR CORREICAO","V"],
          ["00463", "13 SALARIO COMPLEMENTO MINIMO PDF","V"],
          ["00464", "13 SALARIO COMPL DA LEI 14969/11","V"],
          ["00465", "13 SALARIO GRATIF DA LEI 14969/11","V"],
          ["00466", "VANT PESSOAL NOMINALMENTE INDENT","V"],
          ["00467", "ART 5 DA LEI 14.969/2011","V"],
          ["00468", "DEVOLUCAO DE FALTAS","V"],
          ["00469", "DEVOLUCAO REM MAXIMA 13 FUNPECE","V"],
          ["00470", "GRATIF POLICIAMENTO ESPECIALIZADO","V"],
          ["00471", "VANTAGEM PESSOAL INOMINADA","V"],
          ["00472", "GRAT POR ATIVIDADE DE MAGISTERIO","V"],
          ["00473", "DIFERENCA GRAT ATIV MAGISTERIO","V"],
          ["00474", "ANUIDADE OAB DEC 30988/12","V"],
          ["00475", "PARCELA VARIAVEL DE REDISTRIBUICAO","V"],
          ["00476", "DIF PARCEL VARIAVEL REDISTRIBUICAO","V"],
          ["00477", "ABONO DE INTEGRALIZACAO","V"],
          ["00478", "RATEIO PVR FUNDEB","V"],
          ["00479", "GRATIFICACAO DE DESEMPENHO","V"],
          ["00480", "BOLSA ESTUDO FUNPECE","V"],
          ["00481", "DIFERENCA DE RATEIO DO FUNDEB","V"],
          ["00484", "Diferenca De Bolsa Estudo Funp","V"],
          ["00485", "VANTAGEM  PESSOAL DA LEI 11.260/1986","V"],
          ["00555", "AUXILIO SAUDE","V"],
          ["00560", "DIFERENCA DE AUXILIOeCRECHE","V"],
          ["00816", "RESSARCIMENTO PDF","D"],
          ["00880", "RESTITUICAO FUNPECE","D"],
          ["00881", "REMUNERACAO MAXIMA FUNPECE","D"],
          ["00882", "Generali Seguro","D"],
          ["00883", "Rem Maxima Funpece Ferias","D"],
          ["00894", "ASSOC BENEF DOS SUBTEN/SGT e ABSS","D"],
          ["00930", "CONSIG CONSIDERADAS OBRIGATORIAS","D"],
          ["00786", "ASSOC DOS DELEGADOS DE POL CIVIL","D"],
          ["00423", "DIFERENCA PREMIO FUNPECE","V"],
          ["00424", "GRAT ATIVIDADES ESPECIAIS E RISCO","V"],
          ["00426", "COMPLEMENTO DA LEI NO. 14.582","V"],
          ["00427", "GRAT ENCARGOS DESAPROPIACOES PERIC","V"],
          ["00428", "PREMIO DO MERITO FUNCIONAL","V"],
          ["00486", "COMPL PARA RESPONDER CUMULATIVAMENTE","V"],
          ["00773", "ASS DAS PRACAS DA REGIAO DO CARIRI","D"],
          ["00774", "DESCONTO POR SANCAO PENAL","D"],
          ["00775", "DEVOLUCAO DE PENSAO","D"],
          ["00778", "ADIANTAMENTO FUNPECE 13","D"],
          ["00780", "RESSARC REM MAX SEM INCIDENCIA PRE","D"],
          ["00781", "ASSOC DOS SERV DA SEC DA CULTURA","D"],
          ["00782", "APROSPEC","D"],
          ["00785", "RESSARCIMENTO DE MULTA DE TRANSITO","D"],
          ["00787", "CUSTODIA DISCIPLINAR","D"],
          ["00788", "ASSOCIACAO DELEGADOS DA POLICIA CIVIL","D"],
          ["00808", "Ressarc Remum Maxima Exerc Ant","D"],
          ["00812", "ASSOC DOS ADVOGADOS PUBLICO DO CEA","D"],
          ["00813", "ASSOC CEARENSE DE MAGISTRADOS","D"],
          ["00823", "PARCELA DE DIVIDA PARA SUPSEC","D"],
          ["02240", "GRAT EXERCICIO","V"],
          ["02241", "VANT EXERC ANT","V"],
          ["02242", "DESPESA ANULAR","D"],
          ["02243", "DIF 13 SALARIO","V"],
          ["02244", "DEVOL SALDO NEG","D"],
          ["02245", "DIF PREV PARLAM","D"],
          ["02246", "GRAT EXERCICIO","V"],
          ["02247", "BOLSA TRAB/UNIV","V"],
          ["02248", "DEV REM MAXIMA","V"],
          ["02249", "RESSARC SUPSEC","V"],
          ["02250", "DIF PENS CIVIL","V"],
          ["02251", "DIF PEN EX ANTE","V"],
          ["02252", "DESPESA ANULAR","D"],
          ["02253", "PRODUTIVIDADE","V"],
          ["02254", "DEV REM MAXIMA","V"],
          ["02255", "DIF MONTEPIO","V"],
          ["02256", "DESP AN SEM INC","D"],
          ["02257", "APECE SERVICOS","D"],
          ["02258", "APECE","D"],
          ["02259", "DIF PREV PARLAM","D"],
          ["02260", "GRAT EXERCICIO","V"],
          ["02261", "GRAT EXERCICIO","V"],
          ["02262", "GRAT EX DET LOC","V"],
          ["02263", "DEV REM MAXIMA","V"],
          ["02264", "DEV DES C/INCID","V"],
          ["02265", "DEVOL  MONTEPIO","V"],
          ["02266", "DESP ANULAR PCC","D"],
          ["02267", "ADIANT 13 SAL","D"],
          ["02268", "ADIANT PDF 13","D"],
          ["02269", "SINTAF CONVENIO","D"],
          ["02270", "SINTAF","D"],
          ["02271", "GRAT INST P CIV","V"],
          ["02272", "SERV EXTRAORD","V"],
          ["02273", "RESSARC SUPSEC","V"],
          ["02274", "SINPOCE PL SAUD","D"],
          ["02275", "SINPOCE PL SAUD","D"],
          ["02276", "SINPOCE CONVEN","D"],
          ["02277", "GRAT INST P CIV","V"],
          ["02278", "RESSARC SUPSEC","V"],
          ["02279", "SINPOCE PL SAUD","D"],
          ["02280", "SINDICATO 2","D"],
          ["02281", "SINDICATO 2","D"],
          ["02282", "RESSARC REM MAX","D"],
          ["02283", "GRAT EXERCICIO","V"],
          ["02284", "COMPL REMUN","V"],
          ["02285", "GRAT INCEN PROF","V"],
          ["02286", "RESSARC SUPSEC","V"],
          ["02287", "DESPESA ANULAR","D"],
          ["02288", "GRAT RISCO VIDA","V"],
          ["02289", "GRAT NIV UNIV","V"],
          ["02290", "DIF ASC EXE ANT","V"],
          ["02291", "RESSARC SUPSEC","V"],
          ["02292", "GRAT ESP EXERC","V"],
          ["02293", "GAPFS","V"],
          ["02294", "DIF 13 SALARIO","V"],
          ["02295", "DESPESA ANULAR","D"],
          ["02296", "DIF DE PRODUTIV","V"],
          ["02297", "COMPL SUBSIDIO","V"],
          ["02298", "RESSARC SUPSEC","V"],
          ["02299", "DIF S/IN SUPSEC","V"],
          ["02300", "ABONO POL. MIL.","V"],
          ["02301", "ASSOC SERV 1","D"],
          ["02302", "DESPESA ANULAR","D"],
          ["02303", "ASSOC CABOS/SOL","D"],
          ["02304", "ASSOC B. ST/SGT","D"],
          ["02305", "GRAT REP GAB","V"],
          ["02306", "ABONO POL. MIL.","V"],
          ["02307", "ASSOC SERV 1","D"],
          ["02308", "DESPESA ANULAR","D"],
          ["02309", "ASSOC CABOS/SOL","D"],
          ["02310", "CAPBOM","D"],
          ["02311", "ASSOC B. ST/SGT","D"],
          ["02312", "ASSOC SERV 1","D"],
          ["02313", "GRAT INCEN PROF","V"],
          ["02314", "ASSOC SERV 1","D"],
          ["02315", "DESPESA ANULAR","D"],
          ["02316", "SINDESP CONVEN","D"],
          ["02317", "GRAT INCEN PROF","V"],
          ["02318", "ASSOC SERV 1","D"],
          ["02319", "RESSARC SUPSEC","V"],
          ["02320", "DIF PENS CIVIL","V"],
          ["02321", "DIF PEN EX ANT2","V"],
          ["02322", "DESPESA ANULAR","D"],
          ["02323", "GRAT EXERCICIO","V"],
          ["02324", "GRAT ESPECIAL","V"],
          ["02325", "GRA R VIDA P ME","V"],
          ["02326", "DEV REM MAXIMA","V"],
          ["02327", "GRAT EXERCICIO","V"],
          ["02328", "DIF DE GRATIF3","V"],
          ["02329", "DIF DE GRATIF2","V"],
          ["02330", "DIF PENS CIVIL","V"],
          ["02331", "SINDETRAN DIFER","D"],
          ["02332", "SINDETRAN DIFER","D"],
          ["02333", "DIF DE GRATIF","V"],
          ["02334", "ADIC INSALUBRID","V"],
          ["02335", "DIF ABON FERIAS","V"],
          ["02336", "SINSECE MOVA SE","D"],
          ["02337", "REAL PREV SEG","D"],
          ["02338", "ASS CLASSE III","D"],
          ["02339", "FUNDAC ASSIST 1","D"],
          ["02340", "VAN PESSOAL HEI","V"],
          ["02341", "GRAT REG CLASSE","V"],
          ["02342", "SINDICATO 1","D"],
          ["02343", "GRAT CLIMAT S/I","V"],
          ["02344", "GRAT DE VOO","V"],
          ["02345", "DIF GRAT T M CL","V"],
          ["02346", "VANT POR DEC JU","V"],
          ["02347", "RESSARC SUPSEC","V"],
          ["02348", "FUN COMISSIONAD","V"],
          ["02349", "DESPESA ANULAR","D"],
          ["02350", "DIF ABON FERIAS","V"],
          ["02351", "DIF ASCENSAO","V"],
          ["02352", "DIF ASCENSAO","V"],
          ["02353", "DIF ASC EXE ANT","V"],
          ["02354", "DIF ASC EXE ANT","V"],
          ["02355", "UNIMEDeAGREGADO","D"],
          ["02356", "UNIMEDeURGENTE","D"],
          ["02357", "UNIMEDeCOePART","D"],
          ["02358", "HAP VIDAeAGREG","D"],
          ["02359", "HAP VIDAeAPTO","D"],
          ["02360", "RSPP PREV PRIV","D"],
          ["02361", "DIF ABON FERIAS","V"],
          ["02362", "GRAT EXERCICIO","V"],
          ["02363", "PIS PASEP","V"],
          ["02364", "VANT POR DEC JU","V"],
          ["02365", "VANT POR DEC JU","V"],
          ["02366", "VANT EXERC ANT","V"],
          ["02367", "ASSOC SERV 1","D"],
          ["02368", "DEV REM MAXIMA","V"],
          ["02369", "RESSARC SUPSEC","V"],
          ["02370", "DIF PENS CIVIL","V"],
          ["02371", "RESSARC REM MAX","D"],
          ["02372", "DIF REMUNERACA2","V"],
          ["02373", "ASERPUB","D"],
          ["02374", "ASERPUB","D"],
          ["02375", "ASERPUB","D"],
          ["02376", "ASERPUB","D"],
          ["02377", "RSPP PREV PRIV","D"],
          ["02378", "BRADESCOeSEGURO","D"],
          ["02379", "ASERPUB","D"],
          ["02380", "ASERPUB","D"],
          ["02381", "ADIANT 13 SAL","D"],
          ["02382", "ADIANT PDF 13","D"],
          ["02383", "BRADESCOeSEGURO","D"],
          ["02384", "ASERPUB","D"],
          ["02385", "DEV MONT SUPSEC","D"],
          ["02386", "ASERPUB","D"],
          ["02387", "ASSOC SERV 1","D"],
          ["02388", "ASERPUB","D"],
          ["02389", "GRAT ESPECIAL","V"],
          ["02390", "ASERPUB","D"],
          ["02391", "ASSC CONTRIB","D"],
          ["02392", "ASERPUB","D"],
          ["02393", "BRADESCOeSEGURO","D"],
          ["02394", "ASERPUB","D"],
          ["02395", "UNIMED MENSALID","D"],
          ["02396", "DEV P/ SUPSEC","D"],
          ["02397", "ASERPUB","D"],
          ["02398", "ASS CLASSE V","D"],
          ["02399", "DEV P/ SUPSEC","D"],
          ["02400", "ASERPUB","D"],
          ["02401", "APEOC SERVS III","D"],
          ["02402", "BRADESCOeSEGURO","D"],
          ["02403", "ASSOC S C BR C","D"],
          ["02404", "UNIMED","D"],
          ["02405", "ASERPUB","D"],
          ["02406", "BRADESCOeSEGURO","D"],
          ["02407", "ASERPUB","D"],
          ["02408", "DEV P/ SUPSEC","D"],
          ["02409", "ASERPUB","D"],
          ["02410", "ASERPUB","D"],
          ["02411", "GRAT EXERCICIO","V"],
          ["02412", "GRAT ESPECIAL","V"],
          ["02413", "ASERPUB","D"],
          ["02414", "ASERPUB","D"],
          ["02415", "ASERPUB","D"],
          ["02416", "CABEMCE TRANSP","D"],
          ["02417", "IPEC EMP SAUDE","D"],
          ["02418", "DINAM CLUB SEG","D"],
          ["02419", "ASERPUB","D"],
          ["02420", "ASERPUB","D"],
          ["02421", "UNIMED","D"],
          ["02422", "ASERPUB","D"],
          ["02423", "ASERPUB","D"],
          ["02424", "RSPP PREV PRIV","D"],
          ["02425", "ASERPUB","D"],
          ["02426", "ADIANT 13 SAL","D"],
          ["02427", "ADIANT PDF 13","D"],
          ["02428", "ASERPUB","D"],
          ["02429", "ASERPUB","D"],
          ["02430", "ASERPUB","D"],
          ["02431", "DESCONTO CRECHE","D"],
          ["02432", "ASERPUB","D"],
          ["02433", "ASERPUB","D"],
          ["02434", "BRADESCOeSEGURO","D"],
          ["02435", "COMPL SALARIAL","V"],
          ["02436", "ASERPUB","D"],
          ["02437", "ASERPUB","D"],
          ["02438", "DIF 13 SALARIO","V"],
          ["02439", "ASERPUB","D"],
          ["02440", "ASERPUB","D"],
          ["02441", "ASERPUB","D"],
          ["02442", "SINDERT ACORDO2","D"],
          ["02443", "ASERPUB","D"],
          ["02444", "VANT EXERC ANT","V"],
          ["02445", "DEV DES INDEVID","V"],
          ["02446", "ASERPUB","D"],
          ["02447", "GRAT EXERCICIO","V"],
          ["02448", "ASES CONTRIB","D"],
          ["02449", "ASERPUB","D"],
          ["02450", "ASERPUB","D"],
          ["02451", "ASERPUB","D"],
          ["02452", "DIF PEN EX ANTE","V"],
          ["02453", "ASERPUB","D"],
          ["02454", "RESSARC PDF","D"],
          ["02455", "BRADESCOeSEGURO","D"],
          ["02469", "DIF DE PENSAO VITALICIA","V"],
          ["02478", "DIF DE AUXILIO ALIMENTAÇÃO","V"],
          ["02480", "RESSARCIMENTO DA REMUNERACAO MAXIMA SETORIAL","D"],
          ["02491", "DESPESA ANULAR SEM INCIDENCIA","D"],
          ["02493", "RESSARCIMENTO REMUM MAXIMA EXERCICIO ANTERIORES","D"],
          ["02547", "DIFERENÇA DE 13º SALõRIO e SISTEMA","V"],
          ["02555", "PREMIO POR PUBLICACAO DE OBRAS","V"],
          ["02563", "DESCONTO DE LICENCA SAUDE","D"],
          ["2569", "COMPENSACAO POR METAS P/ RED DA CRIMINALIDADE","V"],
          ["11011", "APESC e BRADESCO","D"],
          ["11021", "SINDESP e BANCO RURAL","D"],
          ["11031", "SINDESP e BIC BANCO","D"],
          ["11041", "SINDESP e BNB CLUB","D"],
          ["11051", "SINDESP e OBOE FINANCEIRA","D"],
          ["11061", "CREDFAZ e EMP PROP ASSOCIACAO","D"],
          ["11071", "AORECE e PANAMERICANO","D"],
          ["11081", "AORECE e RS FINANCEIRA","D"],
          ["11091", "SINSESC e BANCO RURAL","D"],
          ["11101", "ASSO  e EMP PROP ASSOCIACAO","D"],
          ["11111", "ACS e OBOECARD","D"],
          ["11121", "SINSESC e HSBC BANK BRASIL S/A","D"],
          ["11131", "ASSEEC e BANCO RURAL","D"],
          ["11141", "SINSESC e OBOE FINANCEIRA","D"],
          ["11151", "ASSEEC e BIC BANCO","D"],
          ["11161", "ASSEEC e EMP PROP ASSOCIACAO","D"],
          ["11171", "SINTAF e BSE S/A","D"],
          ["11181", "AAFI e OBOE FINANCEIRA","D"],
          ["11191", "ASSEMA e BANCO RURAL","D"],
          ["11201", "ASSEDRU e BIC BANCO","D"],
          ["11211", "BANCO BRADESCO S/A e BANCO BRA","D"],
          ["11221", "ASSIDACE e OBOE","D"],
          ["11231", "ASSEMA e FORTBRASIL CARD","D"],
          ["11241", "CAIXA ECONOMICA FEDERAL","D"],
          ["11251", "ASSEMA e HSBC","D"],
          ["11261", "ASERPUB e DAYCOVAL","D"],
          ["11271", "APECE  e OBOE","D"],
          ["11281", "SINDASP e  PANAMERICANO","D"],
          ["11291", "SINDASP e  RS FINANCEIRA","D"],
          ["11301", "CARDS e RS FINANCEIRA","D"],
          ["11311", "SINDER e OBOE CARD","D"],
          ["11321", "APEOC e BANCO RURAL","D"],
          ["11331", "APEOC e OBOE FINANCEIRA","D"],
          ["11341", "APEOC e OBOECARD","D"],
          ["11351", "SINDER e OBOE CARD","D"],
          ["11361", "SINDER e OBOE FINANCEIRA S/A","D"],
          ["11371", "SINPOCI e BIC BANCO","D"],
          ["11381", "SINDER e OBOE FINANCEIRA S/A","D"],
          ["11391", "ASSTDS e OBOE FINANCEIRA","D"],
          ["11401", "APEOC e BANCO ALFA S/A","D"],
          ["11411", "BANCO BRADESCO S/A","D"],
          ["11421", "BANCO BRADESCO LOJA","D"],
          ["11431", "BANCO CAIXA","D"],
          ["11441", "ASSTDS e OBOE FINANCEIRA","D"],
          ["11451", "CAIXA / PANAMERICANO","D"],
          ["11461", "COOPERJURIS","D"],
          ["11471", "UNANIME","D"],
          ["12011", "ASPBRAS e ODONTO/ FINANC","D"],
          ["12021", "ACS e EMPRESTIMO FARDAMENTO (C","D"],
          ["12031", "ASSEPLAN e EMP PROP ASSOCIACAO","D"],
          ["12041", "ASTECE e EMP PROP ASSOCIACAO","D"],
          ["12051", "CABEMCE e LOJA/FARMACIA/SUPERM","D"],
          ["12061", "CAPBOM e SERVICO ASSISTENCIAL","D"],
          ["12071", "FAPECE e EMP PROP ASSOCIACAO","D"],
          ["12081", "ASENMESC e OBOE","D"],
          ["12091", "ASSEDRU e FARC. APESC","D"],
          ["12101", "ASSEDRU e FARC.APESC","D"],
          ["12111", "CAPBOM e DEBITO ASSOCIACAO","D"],
          ["12121", "ASSEDRU e HAPVIDA","D"],
          ["12131", "ASSEDRU e FARC APESC","D"],
          ["12141", "SINDER e EMP PROP ASSOC","D"],
          ["12151", "ASSEDRU e ODONTOART","D"],
          ["12161", "CAPBOM e ODONTOLOGICO DM","D"],
          ["12171", "SINPOCI e EMP PROP ASSOCIACAO","D"],
          ["12181", "ASSEDRU e ORDONTOART","D"],
          ["12191", "GENERALLE e ODONTO/ FINANC","D"],
          ["12201", "ASSEDRU e ORTONTOART","D"],
          ["12211", "ASSEDRU e EMP PROP ASSOCIACAO","D"],
          ["12221", "ASSIDACE e EMP PROP ASSOCIACAO","D"],
          ["12231", "UNIFUNCE e ODONTO/ FINANC","D"],
          ["12241", "ASSETRAN e PROMOCAO","D"],
          ["12251", "ABSS e ASSOC BENEFIC ST SGT","D"],
          ["12261", "HAPVIDA ASSISTENCIA MEDICA LTD","D"],
          ["12271", "ODONTO SYSTEM PLANOS ODONTOLOG","D"],
          ["12281", "ETHERNUS SERV FUNERARIOS LTDA","D"],
          ["12291", "ABS ASSISTENCIA BUCAL SERVICOS","D"],
          ["12301", "ORGANIZACAO NOBRE LTDA","D"],
          ["13011", "APESC e LOJAS ESQUISITA","D"],
          ["13021", "ASSEEC e PAO DE ACUCAR","D"],
          ["13031", "ASSETRAN e LIVRA  INTERATIVA","D"],
          ["13041", "ACS e OTICA GABRIELA","D"],
          ["13051", "CAPBOM e AC AUTO CAR","D"],
          ["13061", "CAPBOM e MARLUCIA JOIAS","D"],
          ["13071", "CAPBOM e ZENIR MOVEIS","D"],
          ["13081", "SINDASP e  OTICA SHALOON","D"],
          ["13091", "SINDETRAN e LIVRARIA PEDRO I","D"],
          ["13101", "SINPOCI e OTICA EVANGELICA","D"],
          ["13111", "SINPOCI e OTICA GABRIELA","D"],
          ["13121", "SINPOCI e CENTRO DOS OCULOS","D"],
          ["13131", "SINPOCI e CRECHE","D"],
          ["13141", "SINPOCI e FORTALEZA OTICA","D"],
          ["13151", "SINPOCI e KAMILLA MODAS","D"],
          ["13161", "SINPOCI e LIVRARIA EDUCATIVA","D"],
          ["13171", "SINPOCI e LIVRARIA PEDRO I","D"],
          ["13181", "SINPOCI e MR GUN","D"],
          ["13191", "SINPOCI e OTICA VISAO","D"],
          ["13201", "SINSESC e CONFECCOES LUZZES","D"],
          ["13211", "SINSESC e DUARTE MOVEIS","D"],
          ["13221", "SINSESC e KAMILA MODAS","D"],
          ["13231", "SINTAF e ACEP","D"],
          ["13241", "SINTAF e BNB CLUBE","D"],
          ["13251", "SINTAF e FARMACIA DOSE CERTA","D"],
          ["13261", "SINTAF e FUND CEARENSE PESQ","D"],
          ["13271", "SINTAF e INSTITUTO","D"],
          ["13281", "SINTAF e INTERSYSTEM","D"],
          ["13291", "SINTAF e TIM NORDESTE","D"],
          ["13301", "AAFI e FARMANOSSA","D"],
          ["13311", "CX. BEN 25 SET e EMP PROP ASSO","D"],
          ["13321", "AAFI e OTICA VISAO","D"],
          ["13331", "AAFI e SUPER LAGOA","D"],
          ["13341", "AORECE e ALO.COM","D"],
          ["13351", "AORECE e AORECE LOJA","D"],
          ["13361", "AORECE e AUTO PECAS PE CICERO","D"],
          ["13371", "AORECE e KAMYLLA MODAS","D"],
          ["13381", "AORECE e SUPER FRANGOLANDIA","D"],
          ["13391", "AORECE e SUPERMERCADO LAGOA","D"],
          ["13401", "APESC e OTICA VISA","D"],
          ["13411", "APESC e OTICA VISAO","D"],
          ["13421", "ASNUT e FRANGOLANDIA","D"],
          ["13431", "ASNUT e OTICA VISAO","D"],
          ["13441", "ASSEEC e FARMACIA DROGA DESCO","D"],
          ["13451", "ASSEEC e LIVRARIA PEDRO I","D"],
          ["13461", "ASSEEC e OTICA ALDEOTA","D"],
          ["13471", "ASSEDRU e MERC. LAGOA","D"],
          ["13481", "ASSEDRU e MERC. LAGOA","D"],
          ["13491", "ASSEDRU e MERC. LAGOA","D"],
          ["13501", "ASSETRAN e OTICA  FORTALEZA","D"],
          ["13511", "ASSETRAN e OTICA  PONTUAL","D"],
          ["13521", "ASSO  e DIPOLY","D"],
          ["13531", "ASSO  e LIVRARIA PEDRO I","D"],
          ["13541", "ASSO  e OTICA GABRIELA","D"],
          ["13551", "ASSO  e PAO DE ACUCAR","D"],
          ["13561", "ACS e OI","D"],
          ["13571", "ASSEMA e FORTALEZA OTICA","D"],
          ["13581", "ASSEPLAN e ARTOTICA","D"],
          ["13591", "ASSEPLAN e ARTVISAO","D"],
          ["13601", "ASSEPLAN e DIPOLY","D"],
          ["13611", "ASSEPLAN e LACQUA DI FIORI","D"],
          ["13621", "ASSEPLAN e TIM CORPORATIVO","D"],
          ["13631", "ASSEPLAN e VIVI ZAP LTDA","D"],
          ["13641", "ASSOFI e FARMACIA DOSE CERTA","D"],
          ["13651", "ASSOFI e OTICA DINIZ","D"],
          ["13661", "CAPBOM e ALO. COM","D"],
          ["13671", "CAPBOM e AUTO ESCOLA CACULA","D"],
          ["13681", "CAPBOM e CLARO","D"],
          ["13691", "CAPBOM e EXCEDENTE CLARO","D"],
          ["13701", "CAPBOM e KAMILLA MODAS","D"],
          ["13711", "CAPBOM e MEGACELL","D"],
          ["13721", "CAPBOM e NUCLEO DE BUSCA E SA","D"],
          ["13731", "CAPBOM e OTICA DINIZ","D"],
          ["13741", "CAPBOM e OTICAS VISA","D"],
          ["13751", "CAPBOM e OTICAS VISAO","D"],
          ["13761", "CAPBOM e TOP MOVEIS","D"],
          ["13771", "CAPBOM e ZENIR MOVEIS MARACAN","D"],
          ["13781", "FARMACIA GENTIL","D"],
          ["13791", "SINDASP e  ART OTICA","D"],
          ["13801", "SINDASP e  FARMACIA DOSE CERTA","D"],
          ["13811", "SINDASP e  KAMYLLA MODAS","D"],
          ["13821", "SINDASP e  OTICA ALDEOTA","D"],
          ["13831", "SINDASP e  OTICA GABRIELA","D"],
          ["13841", "SINDASP e  OTICAS VISAO","D"],
          ["13851", "SINDER e OTICA VISA","D"],
          ["13861", "SINDETRAN e IMPERIAL CESTAS","D"],
          ["13871", "SINDETRAN e OTICA VISA","D"],
          ["13881", "ASPEC e EMP PROP ASSOCIACAO","D"],
          ["13891", "ABSS e EMP PROP ASSOCIACAO","D"],
          ["13901", "ASSEMA e PLANO FUNERARIO PLASA","D"],
          ["13911", "SINDASP e  DIVERSOS SINDEPE","D"],
          ["13921", "AAFI e FARMACIA ALDESUL","D"],
          ["13931", "AORECE e OTICA GABRIELA","D"],
          ["13941", "CAPBOM e COLEGIO JIM WILLSON","D"],
          ["13951", "ASSTDS e OTICA VISAO","D"],
          ["13961", "UNIAO COMERCIO DE ALIMENTOS LT","D"],
          ["13971", "EMPREENDIMENTOS PAGUE MENOS S/","D"],
          ["13981", "ODONTOART PLANOS ODONTOLOGICOS","D"],
          ["13991", "BRADESCO VIDA E PREVIDENCIA","D"],
          ["23011", "MR.GUN","D"],
          ["23021", "WSO","D"],
          ["23081", "OTICA VISAO","D"],
          ["50011", "APEOC e ABS","D"],
          ["50021", "APEOC e ODONTOART","D"],
          ["50031", "APEOC e FREE LIFE","D"],
          ["50041", "APEOC e GOLDEM CLUB","D"],
          ["50051", "APEOC e HAPVIDA","D"],
          ["50061", "APEOC e PAE","D"],
          ["50071", "APEOC e PAR","D"],
          ["50081", "APEOC e UCM","D"],
          ["50231", "APEOC e PLAZA","D"],
          ["51011", "ASJUCEC e ABS","D"],
          ["51091", "ASJUCEC e UNIMED","D"],
          ["51101", "ASJUCEC e DENTALPREV","D"],
          ["52051", "ASNUT e HAPVIDA","D"],
          ["52111", "ASNUT e PREVDENT","D"],
          ["52121", "ASNUT e CABURE","D"],
          ["52231", "ASNUT e PLAZA","D"],
          ["52431", "ASNUT e SUL AMERICA SEGUROS","D"],
          ["53051", "ASSC e HAPVIDA","D"],
          ["53131", "ASSC e NORCLINICAS","D"],
          ["53141", "ASSC e UNIODONTO","D"],
          ["53151", "ASSC e ODONTOSYSTEM","D"],
          ["53161", "ASSC e AGUANAMBI SAUDE","D"],
          ["54021", "ASSEEC e ODONTOART","D"],
          ["54031", "ASSEEC e FREE LIFE","D"],
          ["54231", "ASSEEC e PLAZA","D"],
          ["54461", "ASSEEC e DENTALMASTER","D"],
          ["55051", "ASSEINFRA e HAPVIDA","D"],
          ["55091", "ASSEINFRA e UNIMED","D"],
          ["55141", "ASSEINFRA e UNIODONTO","D"],
          ["55171", "ASSEINFRA e CAMED","D"],
          ["55181", "ASSEINFRA e PREVSAUDE","D"],
          ["55231", "ASSEINFRA e PLAZA","D"],
          ["56051", "ASSETRAN e HAPVIDA","D"],
          ["56091", "ASSETRAN e UNIMED","D"],
          ["56141", "ASSETRAN e UNIODONTO","D"],
          ["56151", "ASSETRAN e ODONTOSYSTEM","D"],
          ["56231", "ASSETRAN e PLAZA","D"],
          ["57051", "ASSEPLAN e HAPVIDA","D"],
          ["57091", "ASSEPLAN e UNIMED","D"],
          ["57141", "ASSEPLAN e UNIODONTO","D"],
          ["57191", "ASSEPLAN e PREVDENTE","D"],
          ["57201", "ASSEPLAN e PARQUE DA SAUDADE","D"],
          ["57231", "ASSEPLAN e PLAZA","D"],
          ["58211", "ASSIDACE e DENTAL SEGUROS","D"],
          ["58231", "ASSIDACE e PLAZA","D"],
          ["59141", "ASSO e UNIODONTO","D"],
          ["59231", "ASSO e PLAZA","D"],
          ["60011", "ACSMCE e ABS","D"],
          ["60051", "ACSMCE e HAPVIDA","D"],
          ["61051", "ASSTDS e HAPVIDA","D"],
          ["62241", "BRADESCO PREVIDENCIA","D"],
          ["63011", "CABEMCE e ABS","D"],
          ["63051", "CABEMCE e HAPVIDA","D"],
          ["63251", "CABEMCE e MONGERAL","D"],
          ["64471", "CAFAZ","D"],
          ["64481", "MPS","D"],
          ["64491", "MPS e CLUBE EXECUTIVOS","D"],
          ["65171", "CAMED","D"],
          ["66011", "CAPBOM e ABS","D"],
          ["66031", "CAPBOM e FREE LIFE","D"],
          ["66051", "CAPBOM e HAPVIDA","D"],
          ["66091", "CAPBOM e UNIMED","D"],
          ["66141", "CAPBOM e UNIODONTO","D"],
          ["66151", "CAPBOM e ODONTOSYSTEM","D"],
          ["66161", "CAPBOM e AGUANAMBI SAUDE","D"],
          ["66251", "CAPBOM e MONGERAL","D"],
          ["66271", "CAPBOM e PECULIO","D"],
          ["66281", "CAPBOM e PAS","D"],
          ["67291", "CAPEMISA","D"],
          ["68051", "CLUBE EXECUTIVOS","D"],
          ["69311", "CORSEC SEGUROS","D"],
          ["70111", "FUNCEME e PREVDENT","D"],
          ["70141", "FUNCEME e UNIODONTO","D"],
          ["71321", "GBOEX","D"],
          ["72331", "GOLDEN CROSS","D"],
          ["73341", "INTERMED","D"],
          ["74351", "MBM PREVIDENCIA","D"],
          ["75251", "MONGERAL","D"],
          ["76151", "ODONTOSYSTEM","D"],
          ["77111", "PREVDENT","D"],
          ["78371", "PREVIMIL PREVIDENCIA PRIVADA","D"],
          ["79391", "RS PREVIDENCIA e INVESTPREV","D"],
          ["80051", "SCUDERIE e HAPVIDA","D"],
          ["81091", "ADEPOL e UNIMED","D"],
          ["81141", "ADEPOL e UNIODONTO","D"],
          ["82011", "SINDENTRAN e ABS","D"],
          ["83051", "SINDER e HAPVIDA","D"],
          ["84051", "SINDESP e HAPVIDA","D"],
          ["84091", "SINDESP e UNIMED","D"],
          ["84141", "SINDESP e UNIODONTO","D"],
          ["84181", "SINDESP e PREVSAUDE","D"],
          ["84401", "SINDESP e UNIDENTAL","D"],
          ["85031", "SINSESC e FREE LIFE","D"],
          ["85051", "SINSESC e HAPVIDA","D"],
          ["85091", "SINSESC e UNIMED","D"],
          ["85141", "SINSESC e UNIODONTO","D"],
          ["85151", "SINSESC e ODONTOSYSTEM","D"],
          ["85181", "SINSESC e PREVSAUDE","D"],
          ["85411", "SINSESC e DENTAL FORTALEZA","D"],
          ["85421", "SINSESC e SANTA RITA","D"],
          ["86051", "HAPVIDA","D"],
          ["87431", "SUL AMERICA SEGUROS","D"],
          ["88091", "UNIMED","D"],
          ["89141", "UNIODONTO","D"],
          ["90441", "TOKIO MARINE","D"],
          ["02704", "DIFERENCA DE PLANTAO","V"],
          ["102", "Subsidios","V"],
          ["103", "Gratificacao De Exercicio","V"],
          ["104", "Gratificacao Especial","V"],
          ["105", "Representacao Da Lei N. 11.535","V"],
          ["106", "Grat P/Exerc Func Em Detet Loc","V"],
          ["107", "Grat Part Em Orgao Deliber E C","V"],
          ["108", "Gratificacao Por Tempo De Serv","V"],
          ["109", "Gratificacao De Representacao","V"],
          ["110", "Gratificacao Abono Policial Ci","V"],
          ["111", "Grat De Risco De Vida Ou Saude","V"],
          ["112", "Grat Pelo Regime De Tempo Inte","V"],
          ["113", "Aditamento De Jornada De Traba","V"],
          ["114", "Diferenca De Vencim/Salario/Su","V"],
          ["115", "Gratificacao De Ensino","V"],
          ["116", "Grat Rep Judicial Consult Juri","V"],
          ["117", "Respondendo Por Cargo Em Comis","V"],
          ["118", "Grat Espec Localizacao Carcera","V"],
          ["119", "Funcao Comissionada","V"],
          ["120", "Gratificacao Dedicacao Exclusi","V"],
          ["121", "Ajuda De Custo","V"],
          ["122", "Diarias","V"],
          ["123", "Substituicao De Cargo Comissio","V"],
          ["124", "Diaria De Campo","V"],
          ["125", "Grat P/ Representacao De Gabin","V"],
          ["126", "Gratificacao De Campo","V"],
          ["127", "Grat Por Servico Ou Estudo For","V"],
          ["128", "Aviso Previo","V"],
          ["129", "Prestacao De Servicos","V"],
          ["130", "Grat Execucao Trab Relev Tec C","V"],
          ["131", "Grat Instrut Curso Policial Ci","V"],
          ["132", "Vantagem Pessoal","V"],
          ["133", "Grat De Funcao Policial Civil","V"],
          ["134", "Grat De Nivel Universitario","V"],
          ["135", "Grat Em Condicoes Especiais","V"],
          ["136", "Ferias Vencidas","V"],
          ["137", "Ferias Proporcionais","V"],
          ["138", "Fgts Art 22","V"],
          ["139", "Produtividade","V"],
          ["140", "Indenizacao De Hora Extra","V"],
          ["141", "Fgts Mes Atual","V"],
          ["142", "Gratificacao De Estipendio","V"],
          ["143", "Fgts Mes Anterior","V"],
          ["144", "Diferenca De Gratificacao","V"],
          ["145", "Gratificacao Da Lei N. 2.394/5","V"],
          ["146", "Grat Da Lei N. 7.066/63  Cotas","V"],
          ["147", "Adicional De Ferias","V"],
          ["148", "Pre-Julgado","V"],
          ["149", "Abono Carcerario","V"],
          ["150", "Hora Extra - 50 Por Cento -","V"],
          ["151", "Hora Extra - 100 Por Cento -","V"],
          ["152", "Dif Serv Extraordinario/Hora E","V"],
          ["153", "Vantagem Incorporada","V"],
          ["154", "Adicional De Insalubridade","V"],
          ["155", "Servico Extraordinario","V"],
          ["156", "Adicional Noturno","V"],
          ["157", "Adiantamento De Ferias","V"],
          ["158", "Adicional Noturno Incorporado","V"],
          ["159", "Gratificacao Da Lei N. 7.486/6","V"],
          ["160", "Diarias Maior Que 50 Por Cento","V"],
          ["161", "Vantagem Pessoal Hei","V"],
          ["162", "Media Ferias","V"],
          ["163", "Adiantamento Do 13 Salario","V"],
          ["164", "Complementacao De Proventos","V"],
          ["165", "Salario Maternidade","V"],
          ["166", "Gratificacao Da Lei N. 4.196/5","V"],
          ["167", "Gratificacao Da Lei N. 7.999/6","V"],
          ["168", "Adicional De Funcao","V"],
          ["169", "Gratificacao Da Lei N. 8.384/6","V"],
          ["170", "Tranferencia De Empregado","V"],
          ["171", "Grat De Representacao Incorpor","V"],
          ["172", "Diferenca De Ferias","V"],
          ["173", "Indenizacao De Licenca Premio","V"],
          ["174", "Pagamento Aulas","V"],
          ["175", "Gratificacao De Plantao Noturn","V"],
          ["176", "Gratificacao Por Eventos","V"],
          ["177", "Abono De Ferias","V"],
          ["178", "Grat T Recursal","V"],
          ["179", "Diferenca De Ascensao","V"],
          ["180", "Gratificacao Comissao De Licit","V"],
          ["181", "Complemento Salarial","V"],
          ["182", "Complemento Salarial - Inss","V"],
          ["183", "Grat De Efetiva Regencia De Cl","V"],
          ["184", "Diferenca De Progressao Horizo","V"],
          ["185", "Grat Efetivo Exerc Especialida","V"],
          ["186", "Grat Profess Pessoas Com Defic","V"],
          ["187", "Devolucao De Remuneracao Maxim","V"],
          ["188", "Indenizacao Ou Auxilio A Morad","V"],
          ["189", "Produtividade Por Decisao Judi","V"],
          ["190", "Devolucao De Imposto De Renda","V"],
          ["191", "Gratificacao Do Artigo 155","V"],
          ["192", "Grat De Pericia Medica E Tecni","V"],
          ["193", "Diferenca De Pensao Alimentici","V"],
          ["194", "Diferenca Decimo Terceiro Sala","V"],
          ["195", "Decimo Terceiro Salario","V"],
          ["196", "Operacao Radar","V"],
          ["197", "Bolsa De Estudo","V"],
          ["198", "Grat De Direcao E Legislacao","V"],
          ["199", "Pensao Alimenticia","V"],
          ["200", "Salario Educacao","V"],
          ["201", "Indenizacao De Representacao","V"],
          ["202", "Soldo / Vencimento","V"],
          ["203", "Gratificacao Por Tempo De Serv","V"],
          ["204", "Indenizacao Funcao Pol Militar","V"],
          ["205", "Grat De Representacao De Gabin","V"],
          ["206", "Grat Exercicio No Interior Est","V"],
          ["207", "Gratificacao Representacao-Mil","V"],
          ["208", "Gratificacao De 1/3 Sobre O So","V"],
          ["209", "Diferenca De Soldo Ou Vencimen","V"],
          ["210", "Indenizacao Da Habilitacao Mil","V"],
          ["211", "Gratificacao De Ensino - Milit","V"],
          ["212", "Gratificacao De Magisterio","V"],
          ["213", "Diferenca De Gratificacao","V"],
          ["214", "Indenizacao De Moradia - Milit","V"],
          ["215", "Grat Risco De Vida/Saude Milit","V"],
          ["216", "Incent Ao Desenvolv Profission","V"],
          ["217", "Gratificacao Atividade Funcion","V"],
          ["218", "Gratificacao Da Lei N. 10.206/","V"],
          ["219", "Devolucao De Fa","V"],
          ["220", "Diferenca De Salario Educacao","V"],
          ["221", "Ajuda De Custo - Militar","V"],
          ["222", "Diarias - Militar","V"],
          ["223", "Etapas Para Alimentacao","V"],
          ["224", "Ajuda Para Fardamento","V"],
          ["225", "Grat De Desempenho Fazendario","V"],
          ["226", "Gratificacao Incentivo Motoris","V"],
          ["227", "Grat De Delegado Ou Subdelegad","V"],
          ["228", "Indenizacao Adicional Inativid","V"],
          ["229", "Diarias Operacionais","V"],
          ["230", "Grat De Licenca Extraordinaria","V"],
          ["231", "Gratificacao Incorporada","V"],
          ["232", "Diferenca Incorporada","V"],
          ["233", "Devolucao Desc Indev S/Inciden","V"],
          ["234", "Vantagem Incorporada Da Saude","V"],
          ["235", "Indenizacao De Ferias","V"],
          ["236", "Vantagem Pessoal Do Pcc","V"],
          ["237", "Incentivo Aperfeicoam E Qualid","V"],
          ["238", "Grat Especial De Desempenho","V"],
          ["239", "Grat Monitoramento Climatico","V"],
          ["240", "Vantagem Por Decisao Judicial","V"],
          ["241", "Grat Desempenho Atividades Obr","V"],
          ["242", "Gratificacao Externa","V"],
          ["243", "Vantagem Incorporada Da Febemc","V"],
          ["244", "Vantagem Pessoal Da Lei 12.287","V"],
          ["245", "Vantagem De Exercicio Anterior","V"],
          ["246", "Ajuda Fardamento Com Restituic","V"],
          ["247", "Emprestimo/Adiantamento De Fer","V"],
          ["248", "Gratificacao De Auditor","V"],
          ["249", "Gratificacao Judiciaria","V"],
          ["250", "Gratificacao De Especializacao","V"],
          ["251", "Gratificacao Da Lei 12.482/95","V"],
          ["252", "Grat Membros Conselho Magistra","V"],
          ["253", "Complemento Remuneratorio","V"],
          ["254", "Diferenca Complem Remuneratori","V"],
          ["255", "Gratificacao De Voo","V"],
          ["256", "Parcela De Desempenho Minister","V"],
          ["257", "Vantagem Pessoal - Quintos","V"],
          ["258", "Abono Compensatorio","V"],
          ["259", "Reposicao De Faltas","V"],
          ["260", "Diferenca De Diarias","V"],
          ["261", "Dif Gratificacao De Representa","V"],
          ["262", "Diferenca Bolsa Trabalho / Est","V"],
          ["263", "Residencia Medica","V"],
          ["264", "Bolsa De Trabalho / Estagio","V"],
          ["265", "Diferenca Urv","V"],
          ["266", "Adiantamento De Salario","V"],
          ["267", "Grat Incentivo Centro Proces D","V"],
          ["268", "Gratificacao De Funcao","V"],
          ["269", "Abono Fazendario","V"],
          ["270", "Parcela Por Decisao Judicial","V"],
          ["271", "Complemento Por Decisao Judici","V"],
          ["272", "Diferenca De Ampliac Carga Hor","V"],
          ["273", "Adicional De Periculosidade","V"],
          ["274", "Adicional De Insalubridade","V"],
          ["275", "Gratificacao De Locomocao","V"],
          ["276", "Memb Junta Rec","V"],
          ["277", "Gratificacao De Projeto","V"],
          ["278", "Auxilio Alimentacao","V"],
          ["279", "Grat Dir Tcm","V"],
          ["280", "Representacao Tcm","V"],
          ["281", "Grat Incentivo Profissional","V"],
          ["282", "Gratificacao Extra Classe","V"],
          ["283", "Grat Execucao Obras E Transpor","V"],
          ["284", "Grat Incent Pesq Desenvolvimen","V"],
          ["285", "Diferenca De Prestacao De Serv","V"],
          ["286", "Parc Ad Desemp","V"],
          ["287", "Gratificacao Conselho Fiscal","V"],
          ["288", "Gratificacao De Instrutor","V"],
          ["289", "Prolabore","V"],
          ["290", "Grat De Trabalho Tecnico-Jurid","V"],
          ["291", "U R P","V"],
          ["292", "Diferenca Ascensao Exerc Anter","V"],
          ["293", "Diferenca P H Exercicio Anteri","V"],
          ["294", "Devolucao Ipec","V"],
          ["295", "Devolucao Pensao Alimen/Rem Ma","V"],
          ["296", "Vant Da Lei 9.660/72 Ex Combat","V"],
          ["297", "Ressarcimento Do Supsec","V"],
          ["298", "Diferenca Diarias Operacionais","V"],
          ["299", "Emprestimo Saldo Negativo","V"],
          ["301", "Provento","V"],
          ["302", "Gratificacao De Representacao","V"],
          ["303", "Indenizacao De Transporte","V"],
          ["304", "Dif Sem Incidencia De Supsec","V"],
          ["305", "Dif Grat Trab Tecnico Relevant","V"],
          ["306", "Devolucao Inss","V"],
          ["307", "Premio Por Desempenho Fiscal","V"],
          ["308", "Diferenca Premio Desempenho Fi","V"],
          ["309", "Auxilio Mestre Da Cultura","V"],
          ["310", "Custas","V"],
          ["311", "Venc Aposentadoria Proporciona","V"],
          ["312", "Percentual De Custas","V"],
          ["313", "Gratificacao Sobre O Venciment","V"],
          ["314", "Grat Esp Radiopatrulhamento Ae","V"],
          ["315", "Gratificacao Remuneratoria","V"],
          ["316", "Ampliacao De Carga Horaria","V"],
          ["317", "Emprestimo Licenca Extraordina","V"],
          ["318", "Vantagem Da Lei 13.250/2002","V"],
          ["319", "Cargo De Provimento Em Comissa","V"],
          ["320", "Remuneracao","V"],
          ["321", "Diferenca De Remuneracao","V"],
          ["322", "Gratificacao Militar","V"],
          ["323", "Gratificacao Qualificacao Poli","V"],
          ["324", "Grat Qualificacao Bomberistica","V"],
          ["325", "Grat Atividade Policia Judicia","V"],
          ["326", "Gratificacao Atividade Judicia","V"],
          ["327", "Grat Atvidade Defensoria Publi","V"],
          ["328", "Grat Desemp De Atividade Audit","V"],
          ["329", "Diferenca De Gdaa","V"],
          ["330", "Grat. Especifica De Procurador","V"],
          ["331", "Dif De Gdaa Exercicio Anterior","V"],
          ["332", "Diferenca De Residencia Medica","V"],
          ["333", "Devolucao Desc Indev C/ Incide","V"],
          ["334", "Gratificacao Especial De Exerc","V"],
          ["335", "Dif. Grat Trab Moni Clim","V"],
          ["336", "Diferenca Grat Especial Desemp","V"],
          ["337", "Gratificacao Representacao Fun","V"],
          ["338", "Auxilio Reclus O","V"],
          ["339", "Diferen A De Auxilio Moradia","V"],
          ["340", "Diferen A De Provento","V"],
          ["341", "Dif Servico Extraordin Rio","V"],
          ["342", "Diferen A Acordo Judicial Dert","V"],
          ["343", "Acordo Judicial Dert","V"],
          ["344", "Auxilio Mensal Temporario","V"],
          ["345", "Dif Auxilio Mensal Temporario","V"],
          ["346", "Gratificacao Por Titulacao","V"],
          ["347", "Premio Por Apreensao De Armas","V"],
          ["348", "Grat Incent Ao Traba C/Qualida","V"],
          ["349", "Ressarcimento De Proventos","V"],
          ["350", "Grat Desemp De Analise De Gest","V"],
          ["351", "Dif Grat Desenp Analise De Ges","V"],
          ["352", "Grat Desemp Ativ Da Tecno Info","V"],
          ["353", "Dif Grat Desenp Ativ Da Tecno","V"],
          ["354", "Grat Desemp De Ativ Planej Orc","V"],
          ["355", "Dif Grat Desemp Planej E Orcam","V"],
          ["356", "Ind Reforco Serv Militar Opera","V"],
          ["357", "Grat De Desemp De Ativid Regul","V"],
          ["358", "Dif Grat De Desemp De Ativid R","V"],
          ["359", "Grat Desemp De Ativ Analis Pol","V"],
          ["360", "Grat. Ativ De Plant Final Sema","V"],
          ["361", "Dif Grat Desemp Ativ Anal Pol","V"],
          ["362", "Grat Rep Aguardando Aposentado","V"],
          ["363", "Grat/Secretario E Diretor Hosp","V"],
          ["364", "Abono Do Grupo Mas","V"],
          ["365", "Diferenca Subsidios","V"],
          ["366", "Diferenca De Pensao Indenizato","V"],
          ["367", "Dif Grat Ded Exclus L 14005/07","V"],
          ["368", "Adiantamento Da Lei 14.112 Apj","V"],
          ["369", "Grat De Policiamento Ostensivo","V"],
          ["370", "Dif De Vantagem Decisao Judici","V"],
          ["371", "Grat Por Encargos De Licitacao","V"],
          ["372", "Complemento Subsidio","V"],
          ["373", "Dif Grat Por Encargos De Licit","V"],
          ["374", "Dif Grat Policiamento Ostensiv","V"],
          ["375", "Parcela Nominalmente Identific","V"],
          ["376", "Grat Comissao Concurso","V"],
          ["377", "Abono De Ferias Sem Incidencia","V"],
          ["378", "Diferenca De Reajuste","V"],
          ["379", "Dif Media Pdf Ferias","V"],
          ["380", "Programa Demissao Voluntaria C","V"],
          ["381", "Indenizacao","V"],
          ["382", "Pensao Aliment Prog Demis Volu","V"],
          ["383", "Pensao Alimenticia - Indenizac","V"],
          ["384", "Pdf 13 Salario","V"],
          ["385", "Adic De Premio Por Desemp Fisc","V"],
          ["386", "Dif Adic De Premio Por Desemp","V"],
          ["387", "Grat De Atividade Medico Peric","V"],
          ["388", "Premio Desempenho Funpece","V"],
          ["389", "Complemento Piso Magisterio","V"],
          ["390", "Grat Por Exerc Na Ativ De Inte","V"],
          ["391", "Complemento De Produtividade","V"],
          ["392", "Abono Magisterio 1 2 Graus","V"],
          ["393", "Auxilio Transporte","V"],
          ["394", "Dif Auxilio Transporte","V"],
          ["395", "Grat Ensino De Praticas Medica","V"],
          ["396", "Grat De Desempenho Ambiental","V"],
          ["397", "Compl Provisorio Da Remun Mini","V"],
          ["398", "Parcela Decisao Judicial/Detra","V"],
          ["399", "Abono Da Lei 14582","V"],
          ["400", "Doacao","V"],
          ["401", "Pensao Militar","V"],
          ["402", "Pensao Civil","V"],
          ["403", "Diferenca Pensao Civil","V"],
          ["404", "Diferenca Pensao Militar","V"],
          ["405", "Diferenca Pensao Exerc Anterio","V"],
          ["406", "Indenizacao Por Acao Judicial","V"],
          ["407", "Funcao Gratificada","V"],
          ["408", "Pensao Especial","V"],
          ["409", "Pensao Indenizatoria","V"],
          ["410", "Plantao Especial","V"],
          ["411", "Gratificacao De Substituicao","V"],
          ["412", "Diferenca Auxilio Alimentacao","V"],
          ["413", "Auxilio Ao Excepcional","V"],
          ["414", "Dif De Vantagem S Incidencia","V"],
          ["415", "Devolucao De Montepio","V"],
          ["416", "Pensao Provisoria","V"],
          ["417", "Diferenca De Pensao Provisoria","V"],
          ["418", "Diferenca Pensao Prov Exerc An","V"],
          ["419", "Diferenca Pensao Especial","V"],
          ["420", "Diferen A De Abono De Permanen","V"],
          ["421", "Pensao Vitalicia","V"],
          ["422", "Diferenca De Pensao Vitalicia","V"],
          ["423", "Diferenca Premio Funpece","V"],
          ["424", "Grat Atividades Especiais E Ri","V"],
          ["425", "Pis Pasep","V"],
          ["426", "Complemento Da Lei No. 14.582","V"],
          ["427", "Grat Encargos Desapropiacoes P","V"],
          ["428", "Premio Do Merito Funcional","V"],
          ["429", "Funcao Com Equipamento Ou Veic","V"],
          ["430", "Abono De Permanencia","V"],
          ["431", "Indenizacao - Morte","V"],
          ["432", "Premio Educacao","V"],
          ["433", "Abono Provisorio","V"],
          ["434", "Adic Individual","V"],
          ["435", "Diferenca De Abono Salarial","V"],
          ["436", "Abono Salarial","V"],
          ["437", "Abono Policial Militar","V"],
          ["438", "Abono Da Lei N. 11.917/1991","V"],
          ["439", "Abono Legista","V"],
          ["440", "Abono Da Lei N.12.541/1995","V"],
          ["441", "Gratificacao De Desempenho Mil","V"],
          ["442", "Premio Aprender Pra Valer","V"],
          ["443", "Funpece Ferias","V"],
          ["444", "Devolucao De Remun Maxima Funp","V"],
          ["445", "Dif De Ascensao Anterior A 200","V"],
          ["446", "Premio Funpece 13 Salario","V"],
          ["447", "Financiamento Cursos Pos Gradu","V"],
          ["448", "Diferenca Piso Magisterio","V"],
          ["449", "Grat Encargo De Analise Calc J","V"],
          ["450", "Grat Desemp Ativ Gerenc Projet","V"],
          ["451", "Compl Do Limite Minimo Pdf","V"],
          ["452", "Dif Compl Minimo Pdf","V"],
          ["453", "Adicional Compl Minimo Pdf Fer","V"],
          ["454", "Dif Adic Compl Minimo Pdf Feri","V"],
          ["455", "Adicional Pdf Ferias","V"],
          ["456", "Dif Adicional Pdf  Ferias","V"],
          ["457", "Grat Da Lei 14.969/2011","V"],
          ["458", "Complemento Da Lei 14.969/2011","V"],
          ["459", "Dif De Pensao Sefaz","V"],
          ["460", "Grat Desemp Ativ Defesa Agrope","V"],
          ["461", "Parc Nomin Identif Lei 15.009/","V"],
          ["462", "Grat Ativ Disciplinar Correica","V"],
          ["463", "13 Salario Complemento Minimo","V"],
          ["464", "13 Salario Compl Da Lei 14969/","V"],
          ["465", "13 Salario Gratif Da Lei 14969","V"],
          ["466", "Vant Pessoal Nominalmente Inde","V"],
          ["467", "Art 5 Da Lei 14.969/2011","V"],
          ["468", "Devolucao De Faltas","V"],
          ["469", "Devolucao Rem Maxima 13 Funpec","V"],
          ["470", "Gratif Policiamento Especializ","V"],
          ["471", "Vantagem Pessoal Inominada","V"],
          ["472", "Grat Por Atividade De Magister","V"],
          ["473", "Diferenca Grat Ativ Magisterio","V"],
          ["474", "Anuidade Oab Dec 30988/12","V"],
          ["475", "Parcela Variavel De Redistribu","V"],
          ["476", "Dif Parcel Variavel Redistribu","V"],
          ["477", "Abono De Integralizacao","V"],
          ["478", "Rateio Pvr Fundeb","V"],
          ["479", "Gratificacao De Desempenho","V"],
          ["480", "Bolsa Estudo Funpece","V"],
          ["481", "Diferenca De Rateio Do Fundeb","V"],
          ["484", "Diferenca De Bolsa Estudo Funp","V"],
          ["485", "Vant Pessoal Da Lei 11.260/198","V"],
          ["486", "Compl P/ Responder Cumulativam","V"],
          ["501", "Salario Familia","V"],
          ["506", "Diferenca De Salario Familia","V"],
          ["551", "Auxilio Doenca","V"],
          ["552", "Auxilio Funeral","V"],
          ["553", "Auxilio Invalidez","V"],
          ["554", "Dif Aux Doenca","V"],
          ["555", "Auxilio Saude","V"],
          ["556", "Auxilio Natalidade","V"],
          ["557", "Auxilio Natalidade","V"],
          ["558", "Diferenca Ou Quebra De Caixa","V"],
          ["559", "Auxilio Creche / Escola","V"],
          ["560", "Diferenca De Auxilio-Creche","V"],
          ["599", "Valor Do Fgts","V"],
          ["601", "Ipec Contrib","D"],
          ["602", "Liq. Recisao","D"],
          ["603", "*              "],
          ["604", "Ipec Emp Saude","D"],
          ["605", "Ipec Emp Simpl","D"],
          ["606", "Ipec Emp Emerg","D"],
          ["608", "Ipec Pec Adic","D"],
          ["609", "Ipec Emp Nupcia","D"],
          ["610", "Assoc S C Br C","D"],
          ["611", "Doacao","D"],
          ["612", "Imposto de Renda","D"],
          ["613", "Indenizacao","D"],
          ["614", "Montep Militar","D"],
          ["615", "Montep Civil","D"],
          ["616", "Aluguel Imovel","D"],
          ["617", "Pensao Aliment","D"],
          ["618", "Aspec Contrib","D"],
          ["619", "Ressarcimento Auxilio Alimenta","D"],
          ["620", "Acspc Contr","D"],
          ["621", "Acspc Serv Colt","D"],
          ["622", "Amb Seguros","D"],
          ["623", "Capemisa Contrib","D"],
          ["624", "Multa Do Trib. De Contas Do Es","D"],
          ["625", "Gboex Contrib","D"],
          ["626", "Federal Seguros","D"],
          ["627", "Assoc Serv 1","D"],
          ["628", "Cia S Minas Br","D"],
          ["629", "Vale Transporte","D"],
          ["630", "Sul Amer Band","D"],
          ["631", "Mongeral Previd","D"],
          ["632", "Odonto System","D"],
          ["633", "Cx Benefic Pmc","D"],
          ["634", "Cx Benefic Seg","D"],
          ["635", "Cx Ben Ser Pres","D"],
          ["636", "Sul Amer S Vida","D"],
          ["637", "Sinsece Mova Se","D"],
          ["638", "Ases Contrib","D"],
          ["639", "Fardamento","D"],
          ["640", "Unidonto","D"],
          ["641", "Unimed","D"],
          ["642", "Cx Ben 25 Set C","D"],
          ["643", "Sameg","D"],
          ["644", "Club Col Fer 1","D"],
          ["645", "Coifa Contrib","D"],
          ["646", "Gr B O Inat C","D"],
          ["647", "Gr B O Inat E","D"],
          ["648", "Conasp","D"],
          ["649", "Aserpub","D"],
          ["650", "Inss","D"],
          ["651", "Aspec Seg Colet","D"],
          ["652", "Real Prev Seg","D"],
          ["653", "Cont Sindical","D"],
          ["654", "Restituicao","D"],
          ["655", "Unasp","D"],
          ["656", "Ass Classe I","D"],
          ["657", "Acm-Assist.Medico Hospitalar","D"],
          ["658", "Atraso","D"],
          ["659", "Faltas","D"],
          ["660", "Despesa Anular","D"],
          ["661", "Despesa Anular Do Salario-Fami","D"],
          ["662", "Rem Maxima","D"],
          ["663", "Ass Classe Ii","D"],
          ["664", "Ass Classe Iii","D"],
          ["665", "Dev Imp Renda","D"],
          ["666", "Dif Pensao Alim","D"],
          ["667", "Hap Vida","D"],
          ["668", "Ressarcimento","D"],
          ["669", "Prevdent","D"],
          ["670", "Cbf A Sp Cont","D"],
          ["671", "Brasilprev","D"],
          ["672", "Cef Emprestimo","D"],
          ["673", "Uniodonto","D"],
          ["674", "Sasec Contrib","D"],
          ["675", "Aspb Contrib","D"],
          ["676", "Aguanambi Saude","D"],
          ["677", "Desafio Jovem","D"],
          ["678", "Previplan Club","D"],
          ["679", "Fortsaude","D"],
          ["680", "Adiant Ferias","D"],
          ["681", "Rspp Prev Priv","D"],
          ["682", "Emprest Ferias","D"],
          ["683", "Fund Esp Pmc","D"],
          ["684", "Fundesp Pmc Ind","D"],
          ["685", "Assoc Ser 2","D"],
          ["686", "Ubasp Contrib","D"],
          ["687", "Fundo Cristao","D"],
          ["688", "Amal Contribuic","D"],
          ["689", "Uniao Benefic De Assiste Serv","D"],
          ["690", "Uisp Seguros","D"],
          ["691", "Ressarc Capes","D"],
          ["692", "Assoc Serv 3","D"],
          ["693", "Cohab-Ce","D"],
          ["694", "Sinfito Ce","D"],
          ["695", "Sind Dos Farmaceutico Do Ceara","D"],
          ["696", "Corrfa Contrib","D"],
          ["697", "Biblioteca Tjc","D"],
          ["698", "Adiant 13 Sal","D"],
          ["699", "Cont Aniversar","D"],
          ["700", "Corsec Seguros","D"],
          ["701", "Caixa Econ Habitacao","D"],
          ["702", "Sintaf","D"],
          ["703", "Yorkshire","D"],
          ["704", "Generali Seguro","D"],
          ["705", "Devol Saldo Neg","D"],
          ["706", "Devol Premio Desempenho Fiscal","D"],
          ["707", "Cafaz Corretora","D"],
          ["708", "Cafaz Indenizac","D"],
          ["709", "Cafaz Dependent","D"],
          ["710", "Diferenca Ipec","D"],
          ["711", "Cafaz","D"],
          ["712", "Ass Classe Iv","D"],
          ["713", "Geplan Contrib","D"],
          ["714", "Auditece","D"],
          ["715", "Casebras","D"],
          ["716", "Assoc Ce Min Pu","D"],
          ["717", "Suspensao","D"],
          ["718", "Gremio Rec Ofic","D"],
          ["719", "Inden Prejuizo","D"],
          ["720", "Club Col Fer 2","D"],
          ["721", "Multa","D"],
          ["722", "Acasp Contrib","D"],
          ["723", "Sindicato 1","D"],
          ["724", "Ressarc  Detran","D"],
          ["725", "Emprest Comum","D"],
          ["726", "Ass.Viuvas.Pmc","D"],
          ["727", "Inst Magist Ce","D"],
          ["728", "Inst Magist Br","D"],
          ["729", "Apece","D"],
          ["730", "Desc Advogado","D"],
          ["731", "Adiant Salario","D"],
          ["732", "Despesa Comprov","D"],
          ["733", "Mont Ser P Br C","D"],
          ["734", "Assoc Eng Agron","D"],
          ["735", "Sind Enge Ce","D"],
          ["736", "Sindicato 2","D"],
          ["737", "Emprest Imobil","D"],
          ["738", "Sindicato 3","D"],
          ["739", "Sind Jornalista","D"],
          ["740", "Sindicato 4","D"],
          ["741", "Sindicato 5","D"],
          ["742", "G B S R","D"],
          ["743", "Rspp Prev Priv","D"],
          ["744", "Dental Seguros","D"],
          ["745", "Lumen  Ad Viam","D"],
          ["746", "Odont Time Life","D"],
          ["747", "Sudameris Emp","D"],
          ["748", "Clindonto","D"],
          ["749", "Bamerindus","D"],
          ["750", "Assist Buc Serv","D"],
          ["751", "Bnb Informatica","D"],
          ["752", "Confunasp Contr","D"],
          ["753", "Confunasp Empre","D"],
          ["754", "Desc Art 124 Vi","D"],
          ["755", "Desconto Creche","D"],
          ["756", "Restaurante Faz","D"],
          ["757", "Irtermed","D"],
          ["758", "Assoc Cabos/Sol","D"],
          ["759", "Unipsico","D"],
          ["760", "Cesta Basica","D"],
          ["761", "Ressarcim H Ext","D"],
          ["762", "Assoc Dos Serv Publicos Brasil","D"],
          ["763", "Mps Seg Grupo","D"],
          ["764", "Cafaz Saude","D"],
          ["765", "Cafaz Estacionamento","D"],
          ["766", "Camed","D"],
          ["767", "Devolucao Abono Permanencia","D"],
          ["768", "Sindert Acordo Judicial","D"],
          ["769", "Unipubli Cont","D"],
          ["770", "Desp Anul S/Pre","D"],
          ["771", "Ausencia","D"],
          ["772", "Ressarcimento Da Remuner. Maxi","D"],
          ["773", "Ass Das Pracas Da Regiao Do Ca","D"],
          ["774", "Desconto Por Sancao Penal","D"],
          ["775", "Devolucao De Pensao","D"],
          ["776", "Ressarcimento Para O Inss","D"],
          ["777", "Dev Previdenc Ampliacao Defini","D"],
          ["778", "Adiantamento Funpece 13","D"],
          ["779", "Assoc Serv 4","D"],
          ["780", "Ressarc Rem Max Sem Incidencia","D"],
          ["781", "Assoc Dos Serv Da Sec Da Cultu","D"],
          ["782", "Aprospec","D"],
          ["783", "Ass Tres Set C","D"],
          ["784", "Ass Tres Set E","D"],
          ["785", "Ressarcimento De Multa De Tran","D"],
          ["786", "Sind Dos Delegados De Pol Civi","D"],
          ["787", "Custodia Disciplinar","D"],
          ["788", "Assoc Delegados Da Policia Civ","D"],
          ["789", "Iprede","D"],
          ["790", "Ass Classe V","D"],
          ["791", "Ass Classe Vi","D"],
          ["792", "Cabemce C Basic","D"],
          ["793", "Cabemce Farmac","D"],
          ["794", "Cabemce Fardam","D"],
          ["795", "Seg Funcionario","D"],
          ["796", "Assoc Serv 5","D"],
          ["797", "Atricon","D"],
          ["798", "Abraccon","D"],
          ["799", "Cabemce Transp","D"],
          ["800", "Cabemce P Saude","D"],
          ["801", "Cabemce P Habit","D"],
          ["802", "Assoc Dos Previdenciarios Serv","D"],
          ["803", "Fonoaudiologa","D"],
          ["804", "Cabemce Emprest","D"],
          ["805", "Des Anul Ferias","D"],
          ["806", "Cohab","D"],
          ["808", "Ressarc Remum Maxima Exerc Ant","D"],
          ["809", "Club Atl B V Se","D"],
          ["810", "Oboe Financeira","D"],
          ["811", "Banco Sudameris","D"],
          ["812", "Assoc Dos Advogados Publico Do","D"],
          ["813", "Assoc Cearense De Magistrados","D"],
          ["815", "Fundo Penitenci","D"],
          ["816", "Ressarcimento Pdf","D"],
          ["820", "Desconto Previdencia","D"],
          ["821", "Devolucao Para Supsec","D"],
          ["822", "Previdencia Parlamentar","D"],
          ["823", "Parcela De Divida Para Supsec","D"],
          ["824", "Ipec Emp Funer","D"],
          ["831", "Ass Nac Min Pub","D"],
          ["834", "Aux Alimentacao","D"],
          ["835", "Devolucao De Proventos","D"],
          ["838", "Indeniz Pen Ali","D"],
          ["839", "Pdvi Pen Alimen","D"],
          ["841", "Previmil Cont","D"],
          ["846", "Capbom - Caixa Assist Peculio","D"],
          ["847", "Gr S Brandinho","D"],
          ["848", "Gr Cabo Anselmo","D"],
          ["850", "Bec Informat 2","D"],
          ["851", "Cia U C Seg A P","D"],
          ["852", "Bec Informat  1","D"],
          ["853", "Bec Seguro","D"],
          ["854", "Bradesco Emprestimo","D"],
          ["855", "Bec Habitacao","D"],
          ["856", "Clube Executivo","D"],
          ["857", "Bic Emprestimo","D"],
          ["858", "Banco Do Brasil - Emprestimo","D"],
          ["860", "Imp S Serv Iss","D"],
          ["862", "Brasil Cred","D"],
          ["865", "Diferenca Inss","D"],
          ["868", "Associbras Cont","D"],
          ["869", "Caspeb","D"],
          ["871", "Dinam Club Seg","D"],
          ["873", "Ufec Contrib","D"],
          ["875", "Proquality Aacc","D"],
          ["878", "Pro-Social Cont","D"],
          ["880", "Restituicao Funpece","D"],
          ["881", "Remuneracao Maxima Funpece","D"],
          ["882", "Generali Seguro","D"],
          ["882", "Generali Seguro","D"],
          ["883", "Rem Maxima Funpece Ferias","D"],
          ["894", "Assoc Benef Dos Subten/Sgt - A","D"],
          ["895", "Pensao Antecipa","D"],
          ["896", "Diferenca Urv","D"],
          ["899", "Emp Saldo Negat","D"],
          ["900", "Cedap  Peixe","D"],
          ["903", "Livraria","D"],
          ["905", "Gnpp Seg Sa Con","D"],
          ["906", "Rspp Prev Priv","D"],
          ["910", "Assc Contribuicao","D"],
          ["911", "Farmacia","D"],
          ["914", "Convenio Sesi","D"],
          ["927", "Uniao Assistencias Dos Serv Br","D"],
          ["930", "Consig Consideradas Obrigatori","D"],
          ["950", "Consignacoes Facultativas","D"],
          ["956", "Ind Acao Judici","D"],
          ["957", "Depo Judicial","D"],
          ["959", "Golden Cross","D"],
          ["967", "Bradesco-Seguro","D"],
          ["978", "Fundac Assist 1","D"],
          ["979", "Fundac Assist 2","D"],
          ["986", "Conta Empregado","D"],
          ["988", "Probal","D"],
          ["994", "Club/Col Fer 3","D"],
          ["995", "Club/Col Fer 4","D"],
          ["996", "Assoc Dos Pracas Da Pm E Bm","D"],
          ["997", "Mbm Contrib","D"],
          ["02668", "GITQ e ATIVIDADE RELEVANTES","V"],
          ["02671", "GITQ e PLANTAO","V"],
          ["02604", "GRAT DE DESEMP DE ATIVIDADE DE GESTÃO URBANA E TERRITORIAL   GDUT","V"],
          ["02602", "ASSEMACE","D"],
          ["02606", "DIFERENÇA DA GDUT","V"],
          ["02612", "DESP ANULAR DE FERIAS S/INCIDENCIA","D"],
          ["02618", "DEPOSITO JUDICIAL2","D"],
          ["02619", "DEVOLUCAO DE ABONO DE PERMANENCIA","D"],
          ["02624", "GDM POR DECISAO JUDICIAL","V"],
          ["02625", "RESSARCIMENTO DE CONSIGNACAO","D"],
          ["02675", "RRA DIF PROVENTO","V"],
          ["02681", "INDENIZACAO DA CODISP","V"],
          ["02682", "DIF ADICIONAL NOTURNO","V"],
          ["02684", "GRATIFICACAO PELO EXERCICIO DE COMANDO","V"],
          ["02687", "PENSAO ALIMENTO DEPOSITO JUDICIAL","D"],
          ["02692", "RESSARC DA REMUNERACAO MAXIMA SETORIAL C/SUPSEC","D"],
          ["02693", "FERIAS NAO USUFRUIDAS","V"],
          ["02694", "RESSARCIMENTO INSS SISTEMA","D"],
          ["02695", "COMPENSAÇÃO FINANCEIRA DE CONSELHEIRO DA ARCE","V"],
          ["02696", "RESSARCIMENTO PLANTAO NOTURNO","D"],
          ["02700", "DEVOLUCAO COMPENSACAO POR METAS P/ RED DA CRIMINALIDADE","D"],
          ["02701", "PARCELA NOMINALMENTE IDENTIFICAVEL DA LEI 2015","V"],
          ["02712", "DIF DE GRATIFICACAO DE ENSINO MILITAR","V"],
          ["02713", "RESSARCIMENTO DE GRATIFICACAO DE ENSINO MILITAR","D"],
          ["02715", "VANTAGEM PESSOAL DA LEI 12.122/93","V"],
          ["02717", "DEV REM MAXIMA SEM PREVIDENCIA","V"],
          ["02718", "DIF GRAT PELO EXERCICIO DE COMANDO","V"],
          ["02721", "DEVOLUCAO FUNPECE","V"],
          ["02723", "RESSARCIMENTO DE DIAS PROPORCIONAIS","D"],
          ["02725", "VENC CARGO COMISSIONADO EXCLUSIVO","V"],
          ["02726", "VANTAGEM PESSOAL ART. 1º DA LEI Nº 10.240/79","V"],
          ["02729", "GRAT DE REFORCO OPERACIONAL EXTRAORDINARIO","V"],
          ["02730", "DIF VENC CARGO COMISSIONADO EXCLUSIVO","V"],
          ["02731", "RESSARCIMENTO DE RRA","D"],
          ["02735", "DIFERENCA DE ADICIONAL NOTURNO","V"],
          ["02737", "ABONO ESPECIAL POR REFORCO OPERACIONAL","V"],
          ["02739", "DIF ABONO ESPECIAL POR REFORCO OPERACIONAL","V"],
          ["02740", "GRAT POR ENCARGO DE GESTAO SOCIOEDUCATIVA - GGS","V"],
          ["02744", "GRAT POR ENCARGO DE ATIVIDADE DO SISTEMA SOCIOEDUCATIVA","V"],
          ["02745", "DIF GRAT ENCARGO SOCIOEDUCATIVO","V"],
          ["02746", "GRAT DE ATIVID EDUCACIONAIS ESPECIALISTAS","V"],
          ["02748", "DEPOSITO JUDICIAL 13","D"],
          ["02750", "DIF DE REFORCO OPERACIONAL EXTRAORDINARIO","V"],
          ["02751", "DESC PREVIDENCIA ART 23 LEI 15797/15","D"],
          ["02752", "DIF DESC PREVIDENCIA ART 23 LEI 15797/15","D"],
          ["02753", "GRAT P/ EXERC FUNC EM DETET LOCAIS S/ SUBSEC","V"],
          ["02754", "EXERCICIO DE ENTRANCIA SUPERIOR DO ART 37 LC 06/97","V"],
          ["02755", "VANT PESSOAL NOMINALMENTE IDENTIFICADA DA LEI Nº 15.070/2011","V"],
          ["02756", "AUX ESPECIAL DE REFORCO A RENDA","V"],
          ["02757", "COMPLEMENTO REMUNERATORIO DA LEI 16.145/2016","V"],
          ["101", "VENCIMENTO/SALARIO/PROVENTO","V"],
          ["02760", "PLANTAO EM FINAIS DE SEMANA","V"],
          ["02762", "GRAT DE  INCENTIVO PROFISSIONAL DA LEI 16.141/2016","V"],
          ["02763", "GRAT DE SERVICOS TECNICOS ESPECIALIZADOS - GSTE","V"],
          ["02764", "DIFERENÇA DE PREVIDÊNCIA DECORRENTE LC Nº 167/2016","D"],
          ["02765", "GRAT DE REP DE GABINETE INATIVO","V"],
          ["02766", "AUX ALIMENTAÇÃO DPG","V"],
          ["02769", "GRATIFICACAO DE DEFESA SOCIAL E CIDADANIA - GDSC","V"],
          ["02778", "DIF REVISAO GERAL C/PREVIDENCIA","V"],
          ["02779", "DIF REVISAO GERAL S/PREVIDENCIA","V"],
          ["02780", "DIF REVISAO GERAL COM PREVIDENCIA MARÇO 11.129%","V"],
          ["02782", "GRAT DESEMPENHO DA LEI Nº 16.241/2017 GRUPO ADO E ANS","V"],
          ["02785", "PREVIDENCIA RRA","D"],
          ["02790", "DIFERENCA REVISAO GERAL C/ PREVIDENCIA","V"],
          ["02795", "DIF PISO MAGISTERIO 11%","V"],
          ["02796", "DIF PISO MAGISTERIO 11,129%","V"],
          ["02797", "SINDICATO DOS DOCENTES DA UECE - SINDUECE","D"],
          ["02798", "SINDICATO DOS DOCENTES DA URCA - SINDURCA","D"],
          ["02799", "SINDICATO DOS DOCENTES DA UVA - SINDIUVA","D"],
          ["02800", "IMPOSTO DE RENDA 13","D"],
          ["02801", "REM MAXIMA 13º","D"],
          ["02805", "SUPSEC 13º","D"],
          ["02806", "INSS 13º","D"],
          ["02809", "DEPOSITO JUDICICIAL4","D"],
          ["02812", "ASSETICE","D"],
          ["02815", "DIF DE GRATICACAO 11%","V"],
          ["02816", "DIF DE GRATIFICACAO 11,129%","V"],
          ["02817", "RESSARCIMENTO AUXILIO ALIMENTACAO SISTEMA","D"],
          ["02819", "DEPOSITO JUDICIAL5","D"],
          ["63141", "SINDESP", "D"]
        ]

        default_proceed_types.each do |proceed_type_data|
          cod_provento = proceed_type_data[0]
          dsc_provento = proceed_type_data[1]
          dsc_tipo = proceed_type_data[2]

          proceed_type = Integration::Servers::ProceedType.find_or_initialize_by({
            cod_provento: cod_provento,
            dsc_provento: dsc_provento,
            dsc_tipo: dsc_tipo
          })

          proceed_type.save
        end
      end
    end
  end
end
